### ISSUE TITLE
Calendar out of UIView Container

### ISSUE THREAD

**Issue by langrulez** [CVCalendar/CVCalendar#101]
Hi,
i have implemented the CVCalendar, but i have problem with the constraints, see picture.
Please help me, i’m am despair.

![ios simulator screen shot 27 07 2015 20 16 33](https://cloud.githubusercontent.com/assets/13526984/8915645/8311822c-34a6-11e5-9d8e-a9757990fca0.png)

**Comment by Mozharovsky** [comment]
Hello @langrulez, 

This is a known issue that seems to be fixed not. Please check out  [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop)  branch with its Demo project. Related issue: #104. 

Please close the issue yourself if it works or let me know!

Regards, 
Eugene

**Comment by ngergo100** [comment]
Can i ask you what is the solution for this "Calendar out of container" problem? I tried everything. I checked the #104 issue, but it's still not working right. (If i give the exact width, it is working, but for different sizes doesn't fit de same size)

**Comment by Mozharovsky** [comment]
Hello @ngergo100, 

How did you set up constraints on a CalendarView? Also please make sure you're using the code from the develop branch. 

Regards, 
Eugene

**Comment by ngergo100** [comment]
I'm using the code from the develop branch.
I have trailing space and leading space set up zero to superview. Height for 300. And top space to "calendarmenuview" set up zero also. I think that is not the right way. How should i modify it? 

I also tried with "Leading edges" and "Trailing Edges", and I tried the equal with menuView too.
