### ISSUE TITLE
Refresh specific days

### ISSUE THREAD

**Issue by bphenriques** [CVCalendar/CVCalendar#103]
Hello, 

Thank you for your work. It was exactly what I needed! Really!

How can I update specific entries of calendar? I.e., trigger suplementaryView, dotView, preliminaryView, etc ?

At the moment I can only refresh the selected dayView (by hacking the subviews). I would really need some refresh mechanism somehow! :)

Keep up the great work!

**Comment by Mozharovsky** [comment]
Hello @bphenriques, 

Thank you for using CVCalendar. 

It doesn't support auxiliary views' update for now. But this will come in the nearest future. I'll keep you updated! 

Regards, 
Eugene

**Comment by bretp3** [comment]
Great project @Mozharovsky,
This thing is very helpful.  I'd love to help out on this if I can.  I'm adding an on/off filter to a project and a simple refresh previous, current and following months will be necessary.

Are you already implementing this?  If not I would appreciate you pointing me in the right direction.

Thanks
