### ISSUE TITLE
Disable automatic transition when clicking dayView

### ISSUE THREAD

**Issue by bphenriques** [CVCalendar/CVCalendar#107]
Hello,

How can I disable automatic transition to previous/next month when clicking on a dayView? This issue is preventing me from selecting some days from the week when they are outside the current month.

If you see the screenshots I am unable to selected either 30 or 31 and September shows those days faded however, when I click, It goes automatically to august.

<img width="487" alt="screen shot 2015-08-11 at 12 48 07" src="https://cloud.githubusercontent.com/assets/4727729/9196850/5955858c-4027-11e5-845d-239fbf7c52f5.png">

Edit: Btw, what's the expected behaviour, August shouldn't be showing 30 and 31?

Edit2: Had to hack in CVCalendarMonthContentViewController:
In performedDaySelection comment presentPreviousView and  and presentNextView method calls

My suggestion would be adding a new method to CVCalendarViewDelegate

**Comment by Mozharovsky** [comment]
Hello @bphenriques, 

Thank you for a suggestion. I'll definitely add these features. As for the missed days, you might have auto layout issues. Make sure you're using the latest CVCalendar version, then try to turn off auto shrink `optional func shouldAnimateResizing() -> Bool` on **CVCalendarViewDelegate**.

Let me know on that!

**Comment by bphenriques** [comment]
Hello,

I updated and the missing days are working now! Thank you!
