### ISSUE TITLE
Week view not working properly

### ISSUE THREAD

**Issue by ngergo100** [CVCalendar/CVCalendar#108]
When i arrive at the end of a month there is twice that week which is in the next month too. It's understandable for a developer but if you are a user i think it's a bit odd. And the label text above should be like for example: "Aug-Sept". It was just a suggestion. 

Thanks for your work! It's a really great job you've done.

**Comment by Mozharovsky** [comment]
Hello @ngergo100, 

Please provide the screenshots!

**Comment by ngergo100** [comment]
Hi! @Mozharovsky,

Here is two screenshots:
http://i.imgur.com/XbaSp5S.jpg
http://i.imgur.com/fuzHLzi.jpg

As you see, when i swipe from right to left at the end of September in week view I got the same week just the October part. The problem is that you see twice a week, i think. It is not really a problem, just it would be more convenient if you see that week just ones too.

**Comment by roymckenzie** [comment]
I have this same issue as well.

**Comment by Mozharovsky** [comment]
Guys, sorry for so late response. We've solved this issue in version **2.0.0**. It'll be live in a matter of weeks.

**Comment by ngergo100** [comment]
Nice! Thank you!

**Comment by roymckenzie** [comment]
:+1:

**Comment by loevdahl** [comment]
I'm also struggling with this issue. So looking forward to 2.0 :+1:

**Comment by DennisDreissen** [comment]
Has this been fixed already?

**Comment by loevdahl** [comment]
I think not, I see this in version 1.2.9

**Comment by jose-rodri** [comment]
I have a problem with the view of the months in tables and devices such as iphone 11 they look like duplicates and in normal devices it looks good I do not understand what I should do to eliminate this problem


<img width="320" alt="Captura de Pantalla 2021-05-31 a la(s) 01 18 13" src="https://user-images.githubusercontent.com/54948919/120148580-14a8a900-c1ae-11eb-9654-8a0012824168.png">
