### ISSUE TITLE
Dots missplacing when switching displaying mode

### ISSUE THREAD

**Issue by dev4dev** [CVCalendar/CVCalendar#109]
If day has dots and you select them they move under the circle, and if you switch display mode to Week mode, they appear inside of the circle.
<img width="487" alt="screenshot 2015-08-13 15 14 27" src="https://cloud.githubusercontent.com/assets/722407/9250523/048f1cea-41ce-11e5-88c4-881a32e72205.png">

**Comment by Mozharovsky** [comment]
Hello @dev4dev, 

Yes, dots might disappear since in the Demo project we set them randomly. :) 

Try to set them constantly and you will see the difference!

**Comment by dev4dev** [comment]
nope, you didn't understand. it's a visual bug. I set those dots to be permanent.

**Comment by Mozharovsky** [comment]
Oh, Sorry. I'll check it out! :]

**Comment by lalithagolla** [comment]
Hi Mozharovsky,

How to set dot markers randomly, am getting the dates from json and stored in array. How to add those dates to calendar as a dot. Please help me out
