### ISSUE TITLE
How exactly DayView size is calculated [Help]

### ISSUE THREAD

**Issue by DrAma999** [CVCalendar/CVCalendar#110]
I'm trying to make the calendar view height variable between different devices by giving some conflicting constraint to the calendar view itself and a table view right after it. This because in smaller devices I'd like that at least 2 rows can be visible. I'm configuring everything in storyboard.
As you can see from the screenshot, the calendar view (dark green) has one height constraint with a lower priority (@900) and a constant value of 280pts. Under there is another view (gray) that has a grater than or equal height to 80pts with a required priority.
![schermata 2015-08-19 alle 15 34 23](https://cloud.githubusercontent.com/assets/958522/9357546/d9fe7cd2-4687-11e5-9536-a0c006877875.png)
I'm expecting that in bigger screen the calendar view stays at 280pts, in slower the conflicting condition would require the gray view height constraint to win over the calendar view height.
The problem is that on smaller screen the calendar day size calculation always skip the extra row needed for 6 weeks month representation. This doens't happen in the provided demo or if I fix only the height of the calendar view.
I was able to make it work by change those lines of code:

``` swift
func commitCalendarViewUpdate() {
        if let delegate = delegate, let contentController = contentController {
            let contentViewSize = contentController.bounds.size
            let selfSize = bounds.size

            if !validated {
                let width = selfSize.width
                let height: CGFloat
                let countOfWeeks = CGFloat(6) // <-------------- It was 5

                let vSpace = appearance.spaceBetweenWeekViews!
                let hSpace = appearance.spaceBetweenDayViews!
```

Everything seems to work, but I'm wondering if there is another (better) way to do that.

**Comment by Mozharovsky** [comment]
Hello @DrAma999, 

Try to use the most recent code. I've fixed a couple auto layout issues. Also try to turn off auto shrinking by returning false on `optional func shouldAnimateResizing() -> Bool` (declared in **CVCalendarViewDelegate**). 

Please let me know on your progress!

**Comment by Johnykutty** [comment]
Hi @Mozharovsky. I am using CVCalendar 1.4.1.
In my application the total height of calendar view is increasing when I change month and select days few times. Its happening randomly. 
Could you please suggest whether there is anything I missed or any workaround for fixing this?

Adding screenshots below
![thumb_img_3729_1024](https://cloud.githubusercontent.com/assets/1732366/22725384/1d0c7812-edf3-11e6-8699-cf74845b6cf4.jpg)
![thumb_img_3732_1024](https://cloud.githubusercontent.com/assets/1732366/22725391/1d8ceaba-edf3-11e6-940c-fd4ecb2a6e50.jpg)
![thumb_img_3734_1024](https://cloud.githubusercontent.com/assets/1732366/22725389/1d86c7d4-edf3-11e6-919e-4d6c752d6ac0.jpg)
![thumb_img_3736_1024](https://cloud.githubusercontent.com/assets/1732366/22725386/1d7a995a-edf3-11e6-9669-16a556e5301c.jpg)
