### ISSUE TITLE
Crashing in ios 7.1

### ISSUE THREAD

**Issue by ravifullestop** [CVCalendar/CVCalendar#112]
Please correct it asap.

**Comment by jordibruin** [comment]
Maybe ask for it nicely instead of demanding it be fixed. This only works with iOS 8 + so it will not work on iOS 7.1.

**Comment by Mozharovsky** [comment]
Guys, sorry for late response. iOS 7 will be supported in v**2.0.0**. It'll be live in a matter of weeks.
