### ISSUE TITLE
CVCalendar Height

### ISSUE THREAD

**Issue by omernave** [CVCalendar/CVCalendar#116]
Is there a way to know the height the CVCalendarView need in order to display all of the days properly?
When I use it on an iPhone 5 or newer it looks fine but when I use it on an iPhone 4 it looks bad.

the constraint I have on the calendarView are:
    -leading space to superview: 0
    -trailing space to superview: 0
    -top space to menuView: 0
    -button space to label*: -10

the label is centered at the middle of the view because I have a tableView below the calendarView, the problem, as I said is that when I switch to a smaller screen the calendarView doesn't have enough space.

![screen shot 2015-09-18 at 17 53 33](https://cloud.githubusercontent.com/assets/12939362/9962398/39de1b04-5e2e-11e5-92f3-029b2851a3f7.png)

**Comment by Mozharovsky** [comment]
@omernave: For now all you should do is to play with the height constraint. We'll add labels; auto sizing in v**2.0.0**.
