### ISSUE TITLE
Error Design when the current day has a Event DotMark

### ISSUE THREAD

**Issue by jose920405** [CVCalendar/CVCalendar#119]
![screen shot 2015-09-24 at 12 12 31 pm](https://cloud.githubusercontent.com/assets/12536184/10080491/8dcd41fa-62b5-11e5-9dc6-c830f6d9b228.png)

**Comment by jose920405** [comment]
1 month and nothing?

**Comment by elsesiy** [comment]
@jose920405 Sorry for the delayed repsonse, we're quite busy at the moment. Can you please provide some information on how to reproduce the problem? Thank you!

**Comment by jose920405** [comment]
@elsesiy just create an event in the current day.

In the attached image the event exist in the 24th day

**Comment by jose920405** [comment]
Swift 1.2. Version 1.1.4

**Comment by Mozharovsky** [comment]
@jose920405: Is it still a problem?
