### ISSUE TITLE
preliminaryView error with DayView

### ISSUE THREAD

**Issue by nexon** [CVCalendar/CVCalendar#121]
Hi, i implemented `func preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool` to know when i can draw a specific `preliminaryView` the point is that on the current month works great, but when i change to another month, the **dayView.date** return nil. and i can't do anything (process information according to the date).

<img width="505" alt="captura de pantalla 2015-09-28 a las 9 48 24" src="https://cloud.githubusercontent.com/assets/13189/10135688/6758ab18-65c6-11e5-8637-3ec40205952e.png">

**Comment by Havusoft** [comment]
I have this same problem in supplementaryView. When I change month the dayView returns nil.

**Comment by Mozharovsky** [comment]
@nexon: Thank you for the reported issue! Is it still actual?
