### ISSUE TITLE
CVCalendarView does not appear when displayed in a scrollview

### ISSUE THREAD

**Issue by jmhooper** [CVCalendar/CVCalendar#128]
I'm trying to display a `CVCalendarView` and a `CVCalendarMenuView` in a `UIScrollView` with no success. I've got everything wired up in the storyboard. It works fine until I embed the calendar view and the calendar menu view in a scroll view.

Here's the result of embedding the views in a scrollview:

![image](https://cloud.githubusercontent.com/assets/963654/10384619/ba73467e-6e03-11e5-92d0-2afee6da61c9.png)

As you can see, no calendar view. Also, the menu does not layout properly.

I've got an example project that I setup to demonstrate the problem. [Here's the link](https://github.com/jmhooper/CVCalendar-ScrollView-Bug-Example).

**Comment by imfractured** [comment]
I'm having the same issue except trying to get it into a tableviewheader. I haven't spent too much time with it, but it looks like the size of the view vs the size of the device window in CVCalendarView.swift on line 185 is having issues when its a child of another scrollview / tableview / collection. It seems there are some issues with autolayout as soon as the constraints are initialized when using a xib tableviewheader view with the same setup mentioned in the readme.

**Comment by iChauster** [comment]
Yeah, I had the same problem with the CalendarView laying out properly. After changing some constraints (don't focus on width/height constraints, use spacing constraints to the nearest neighbor), I got it to work.

**Comment by jmhooper** [comment]
@iChauster: If you don't mind me asking, where you doing this in a UIScrollView? If so how did you manage to do so without having problems ambiguous scrollable content size?

**Comment by Isuru-Nanayakkara** [comment]
I'm having this issue as well. I have a view inside a scroll view as the content view which I add the other sub views (menu view, calendar view). When the view controller is loaded, the calendar view doesn't appear. If I rotate the phone to landscape and again rotate it back to portrait, then the calendar shows up.
