### ISSUE TITLE
Daily Calendar

### ISSUE THREAD

**Issue by ridvank** [CVCalendar/CVCalendar#135]
Hi. I have examined CVCalendar project and i like it really. Do you have any feature on showing daily calendar?

**Comment by elsesiy** [comment]
Can you please elaborate on what you exactly want to know? Thanks!

**Comment by ridvank** [comment]
Of course. What i mean is showin hours in the day for the daily calendar. Such as:
![screenshot](https://cloud.githubusercontent.com/assets/6060649/10577054/8ebf690c-7670-11e5-946e-27925919c665.png)

**Comment by elsesiy** [comment]
@ridvank Unfortunately this isn't part of the lib at the moment, but we may consider it for a future release. @Mozharovsky What do you think?

**Comment by Mozharovsky** [comment]
@elsesiy, please contact me via email, I don't see yours. :]
