### ISSUE TITLE
Customize color on specific dates in calendar

### ISSUE THREAD

**Issue by francisykl** [CVCalendar/CVCalendar#139]
Is it possible to customize colors on specific dates instead of all dates at once?

**Comment by elsesiy** [comment]
@francisykl Sorry for the delayed response, we're quite busy at the moment. Just to have a clear understanding, you want to customize the color of each day on selection individually? Or do you mean the dot markers?

**Comment by francisykl** [comment]
I meant the former -  customizing the color of each day on selection individually

**Comment by davidrusu** [comment]
@francisykl @elsesiy 
I'm trying to get this working as well. Any word on if this is possible?

**Comment by elsesiy** [comment]
@davidrusu Nope not atm, we haven't had the time to add features in the last couple weeks but I'll try my best to get it done soon...

**Comment by slyfox4** [comment]
@elsesiy Ii will be great if we will can change color of Weekends. Just like in Apple Calendar to gray.
