### ISSUE TITLE
Is there a way to set background color for the "out" days view?

### ISSUE THREAD

**Issue by Struki84** [CVCalendar/CVCalendar#142]

**Comment by elsesiy** [comment]
@Struki84 Currently not no, IMHO it'll look weird to have a different background for a certain part of the view. What are you trying to achieve?

**Comment by Struki84** [comment]
I was thinking something like this: 
<img width="373" alt="screen shot 2015-10-24 at 12 47 20" src="https://cloud.githubusercontent.com/assets/1117750/10710188/6d091df4-7a4d-11e5-9e1d-9a8ae801f0d8.png">
This calendar has a little more "boxed in" view. Could be I understood something wrong. I just want put all the days not in the current month in something like those grey boxes.

**Comment by Mozharovsky** [comment]
@Struki84, this makes sense. I think we should consider implementing this feature. Thank you for the suggestion! 

@elsesiy, we need to add issues with Bugs, Enhancements and Questions. Like #28

**Comment by elsesiy** [comment]
@Mozharovsky Alright, hit me up on Skype so we can discuss further :+1:
