### ISSUE TITLE
Problem while switching between week view and month view

### ISSUE THREAD

**Issue by Struki84** [CVCalendar/CVCalendar#144]
1. When I set default view to be week view, this is what I get. 
   ![screen shot 2015-10-26 at 16 26 25](https://cloud.githubusercontent.com/assets/1117750/10733867/ddc08258-7c00-11e5-9e29-18b3b6c394a0.png)
   I've tried to find out how is this happening, but without digging in the cocoa pod, I can't say much. 
   As far as I can tell when setting autolayout constraints in IB, there are some constraints that don't render calendar view at all, I think it is the answer to my previous problem https://github.com/Mozharovsky/CVCalendar/issues/141. When I set trailing or leading space to Container margin the calendar won't render at all. 
2. When I get the calendar view to render, the week/month view toggle (`CKCalendarView.changeMode()`) does nothing, I think it's also a constraints problems and how you need to setup auto layout.

**Comment by joelwass** [comment]
use the same constraints as in the demo project

**Comment by Struki84** [comment]
what constraints? For witch element?
