### ISSUE TITLE
What is the logic for return dates in shouldShowOnDayView

### ISSUE THREAD

**Issue by jose920405** [CVCalendar/CVCalendar#146]
Sometimes return dates two months ago, sometimes returned 2 months later. Sometimes only the current month.

I want to render only events of the current month, but often not even return dates for the current month to render events with points.

**Comment by joelwass** [comment]
It's a way to load the views that are likely to be shown when swiping to the next or previous months.... It shouldn't cause an issue when displaying your events on the calendar, what is the issue you're having?
