### ISSUE TITLE
how to start the calendar in a preset date ¿?

### ISSUE THREAD

**Issue by acidfilez** [CVCalendar/CVCalendar#150]
I want to start the calendar in the future, try everthing like: togglePresentedDate(), etc.

Note: Calendar always starts on the current month.

Thanks

**Comment by joelwass** [comment]
you can't as of now, i'll work on it but generally that isn't the use of this project.

**Comment by ahmetalsan** [comment]
i need this too :( anyone can help us?

**Comment by joelwass** [comment]
still not possible, i can work on it over the next week or so

**Comment by dhruv-jindal** [comment]
Is this issue solved as i need it urgently ?
