### ISSUE TITLE
Lose selected date scrolling from month to month

### ISSUE THREAD

**Issue by dlange98** [CVCalendar/CVCalendar#161]
A user selects a date, then scrolls to the next or previous month. The user scrolls back to the original month (that contains the selected date). The selected date is not highlighted, but if the user touches the 'selected date' the calendar does not respond (that date is not highlighted). I'd like to be able to keep the currently selected date as the user scrolls from month to month and back again. As a work around, I tried to find a method to select a date manually, but was unable.

**Comment by LadyDeveloper** [comment]
You can save the selected "DayView" in "didSelectDayView:" method in a global variable in one global file for the app, and select the view in viewWillAppear method, like this: 

func didSelectDayView(dayView: DayView) {
        Utility.sharedInstance.dayViewSelected = dayView
        selectedDay = dayView
}

 override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        if let day = Utility.sharedInstance.dayViewSelected {
            let date = day.date
            let controller = calendarView.contentController as! CVCalendarMonthContentViewController
            controller.selectDayViewWithDay(date.day, inMonthView: controller.presentedMonthView)
        }
}

This work for me.

**Comment by vndn-developers** [comment]
Thanks. It work prefectly.
