### ISSUE TITLE
Changing firstWeekday() messes up with matchedWeeks calculation

### ISSUE THREAD

**Issue by MagnusKloeveKjaer** [CVCalendar/CVCalendar#162]
First of all, great work! And second of all, I'm fairly new at programming, and therefore my terminology may be a bit off - bear with me!

Then...

After changing the first day of the week to Monday instead of Sunday, I realised that toggleViewWithDate() would sometimes screw up the dayView animation. Using the debug tool I discovered that matchedWeeks by mistake return false, even though the days were in the same week, resulting in a dayView selection animation as if the weekView would scroll too.

The matchedWeeks takes two dates as parameters, and is comparing the year, month and week of both CVDates. Since the week of a CVDate is set based on .weekOfMonth, the created dates will not take firstWeekDay() into consideration, and therefore the matchedWeeks will sometimes return false even though it isn't supposed to.

**Comment by Incyc** [comment]
How are you changing the first day of week? I'm guessing you have to make the calendar reload itself and call the firstWeekday delegate call again?
