### ISSUE TITLE
Is there a way of getting six rows worth of days (permanently) rather than 5?

### ISSUE THREAD

**Issue by cyrilzakka** [CVCalendar/CVCalendar#167]
Currently for each month, there are 5 rows. Occasionally the calendar expands to show 6 rows. Is there any possible way of always showing 6 rows?

**Comment by Archivus** [comment]
In other words, I'd like to increase the number of week out days being shown. I've tried playing around with some of the private functions but to no avail :(

**Comment by shidelinFYH** [comment]
@Archivus I have the same problems. Did you solve this? Please help

**Comment by patchthecode** [comment]
@shidelinFYH I was just about to suggest to you the one I was working on. But i'm glad you checked it out yourself. Do you mind telling me where you found it from? I am trying to raise more publicity for it.
