### ISSUE TITLE
didSelectDayView not called anymore

### ISSUE THREAD

**Issue by DennisDreissen** [CVCalendar/CVCalendar#171]
I've updated the CVCalendar pod yesterday, and now the didSelectDayView method isn't being called anymore. Has anything changed lately that could cause this?

**Comment by DennisDreissen** [comment]
Somehow, when I add "animationDidFinish: Bool" to the didSelectDayView method, it just doesn't get called anymore. It works again after I remove it.

**Comment by osmantuna** [comment]
I had same problem and did exactly same thing. I guess they changed overload for that method. It was little bit unnecessary i think.

**Comment by mitchellporter** [comment]
Docs / example needs to be updated. Will submit a PR soon.
