### ISSUE TITLE
How to gray out / prevent selection of past days ?

### ISSUE THREAD

**Issue by MaxIsMyName** [CVCalendar/CVCalendar#172]
Hi,

Thanks for the project, looks great! I am having trouble understanding how to prevent users from selecting days in the past however.

I saw that this is supported as of 1.1.0 but cannot figure how to do so.

A little help would be greatly appreciated. Thank you.

**Comment by Archivus** [comment]
Override didSelectDayView and compare the current date to the day selected. Write if conditions appropriately.

**Comment by Osahamed** [comment]
how can I cancel the selected day, because didSelectDayView is called after the select action not before.
