### ISSUE TITLE
No implementation of dotMarker:colorOnDayView creates fatal error

### ISSUE THREAD

**Issue by FranzBusch** [CVCalendar/CVCalendar#173]
If you implement the delegate function `dotMarker:shouldShowOnDayView` without implementing `dotMarker:colorOnDayView?`  it will lead to:
`fatal error: unexpectedly found nil while unwrapping an Optional value`

The source should be line 256 in the CVCalendarDayView class: `let colors = isOut ? [.grayColor()] : delegate.dotMarker?(colorOnDayView: self)` and the following force unwrapping in line 264. 
`colors` will be nil if the delegate method is not implemented.

**Comment by elsesiy** [comment]
@FranzBusch Alright, I'll look into that in the upcoming week..
