### ISSUE TITLE
How to disable day selection entirely?

### ISSUE THREAD

**Issue by seenickcode** [CVCalendar/CVCalendar#174]
Hello, I've been looking through the code and it doesn't seem like there is way to completely disable day selection.  Specifically, I do not want a blue circle to appear when a tap a day.  

It seems the only way to do this is to override the animations via `CVCalendarViewAnimatorDelegate`

Is there a better way?

Thanks,

**Comment by spandana-batchu** [comment]
Im looking to disable the circle that comes on a selection of a dayView too. Have you found a solution ?

**Comment by bigmotive** [comment]
Anyone figure this out?
