### ISSUE TITLE
Monthly calendar view is out of bounds in CVCalendarView and misaligned with MenuView

### ISSUE THREAD

**Issue by spilja** [CVCalendar/CVCalendar#176]
I'm using the code from develop branch and almost exact autolayout setup as in the demo project. The demo project works fine for me, but I can't get my own to work properly. I tried looking up other issues, people either resolved them by using develop branch code or they didn't get any resolution.

Here's a screenshot of my issue.
<img width="487" alt="screenshot 2015-11-30 19 05 25" src="https://cloud.githubusercontent.com/assets/389595/11480032/90913026-9795-11e5-9ef9-4a80bb04e255.png">

**Comment by tommypacker** [comment]
Getting the same issues here

**Comment by elsesiy** [comment]
Please provide some information on what you've tried so far and how your setup is different from the one provided in the Demo Project, otherwise we won't be able to help you out..
