### ISSUE TITLE
Only allow a date range to be displayed?

### ISSUE THREAD

**Issue by sabernar** [CVCalendar/CVCalendar#178]
Is there any way to prevent the user from choosing dates before/after a specific date?  For example, not allowing the user to choose any date in the future.

**Comment by SASDOE** [comment]
+1 but for past dates

**Comment by berzinsk** [comment]
+1 from me also about not allowing to choose future dates. Would be nice

**Comment by Prarik** [comment]
Really thankful for making this awesome library !!!! 

+1 from me to range selection may be like startDate - 01/01/2015 to endDate - 31/12/2015 
Next step you can add holidays (which can't be selected) within above startDate - endDate like 
holidaysArray = [26/01/2015, 15/08,2015, 25/12/2015]

**Comment by emjoseph** [comment]
+1 for limiting date selection as mentioned above
