### ISSUE TITLE
Improve code for snapping back to current date animation

### ISSUE THREAD

**Issue by AAFFTechnologies** [CVCalendar/CVCalendar#185]
Didn't see this anywhere so I figured I'd ask, is there a way to switch back to the current date? Like for instance say the user is on December 22nd, 2016, and they want to switch back to today (December 1-, 2015), is there a way for them to press a button/bar button to execute this? 

Great piece of software by the way! :-)

**Comment by Archivus** [comment]
Hey this is how I've managed to achieve just that with a nice animation. It involves modifying a file though. First off what I did was place a UITapGestureRecognizer to the title of my navigation bar. The tap gesture called the following function: 
```
func returnToday(tap: UIGestureRecognizer) {
    self.calendarView.toggleCurrentDayView()
}
```
This does exactly what you ask, but the animation is very meh. So I went it and modified the function of a single file. In CVCalendarMonthContentViewController.swift replace the part before `if !matchedDays(selectedDate, presentedDate) && !togglingBlocked {` in `public override func togglePresentedDate(date: NSDate) {}` function with this: 
```
enum ScrollDirection {
       case Left, Right
    }

    private var togglingBlocked = false
    public override func togglePresentedDate(date: NSDate) {
        var scrollDirection : ScrollDirection
        let presentedDate = Date(date: date)
        if let presented = monthViews[Presented], let selectedDate = calendarView.coordinator.selectedDayView?.date {
            
            // Comparing dates to set the direction of the scroll
            if presentedDate.year > selectedDate.year {
                scrollDirection = .Right
            } else if presentedDate.year < selectedDate.year {
                scrollDirection = .Left
            } else {
                if presentedDate.month > selectedDate.month {
                    scrollDirection = .Right
                } else {
                    scrollDirection = .Left
                }
            }
```

**Comment by elsesiy** [comment]
As mentioned by @Archivus using `toggleCurrentDayView()` is exactly what you're asking for, hence -> closed

**Comment by AAFFTechnologies** [comment]
@Archivus  Perfect, thank you much, works like a charm!

**Comment by danielbmarques** [comment]
@elsesiy, @Archivus' animation is really _a lot_ better than the the default one. Can I make a PR replacing it?

**Comment by elsesiy** [comment]
@danielbmarques Go ahead :+1:

**Comment by Archivus** [comment]
I just want to add that there's probably a cleaner way of achieving the animation, I just hacked that up because release date for my project was fast approaching @danielbmarques @elsesiy

**Comment by danielbmarques** [comment]
Ok, I sent in the PR with @Archivus's animation (thanks, it looks great!).
@elsesiy, considering his last message, it might be a good idea to reopen this issue (and maybe rename it) until someone has the time to improve this code.
