### ISSUE TITLE
didShowNextMonthView and didShowPreviousMonthView not being called

### ISSUE THREAD

**Issue by thomasbaldwin** [CVCalendar/CVCalendar#188]
This method isn't getting called for me. Other methods such as didSelectDayView and presentedDateUpdated are working and being called, but not these 2 methods: didSelectDayView
presentedDateUpdated

**Comment by thomasbaldwin** [comment]
The issue was that presentPreviousView wasn't calling the delegate method `didShowPreviousMonthView?(previous.date)` and presentNextView wasn't calling the delegate method `didShowNextMonthView?(following.date)`, so when I would switch months by clicking on a date outside the current month, those method wouldn't be fired.


```swift
self.calendarView.delegate?.didShowPreviousMonthView?(previous.date) // change

**Comment by blwinters** [comment]
I've seen this problem as well. The methods are called when swiping to change the current month, but not if I change the month by tapping on a date in the previous or next month.

**Comment by zdima** [comment]
The issue with these methods is still exists in 1.4.1. 
This is a very basic functionality to let delegate know about view changes irrespectively of what cause the change.
