### ISSUE TITLE
How to change the text color of a non-selected date

### ISSUE THREAD

**Issue by DennisDreissen** [CVCalendar/CVCalendar#191]
I'm trying to change the black color of non-selected circles, but I can't find the correct setting variable. I tried every possible one in CVCalendarViewAppearance.swift.

![Image](http://puu.sh/lZ3NN/c896173fdd.png)

**Comment by neugartf** [comment]
```
  func dayLabelWeekdayInTextColor() -> UIColor {
        return UIColor.redColor()
    }
```

Should work flawlessly here, can you confirm?

**Comment by manjuhere** [comment]
how do i change colors for each of unselected days, based on number of events I have that day? like green if just 1 event, orange if 5 events and red if 10?

**Comment by 2pio** [comment]
@neugartf `dayLabelWeekdayInTextColor` is not working for me, the color is still black
