### ISSUE TITLE
Date selection after dot marker setup

### ISSUE THREAD

**Issue by KimPark89** [CVCalendar/CVCalendar#194]
Hi,
actually inside presentedDateUpdated() I download a json with the dates with an event.
Then I call refreshPresentedMonth() to update the dots (I put a colored dot only on dates with an event).
The problem is that if I have an event on the selected date, I lose the dot (probably because the selection didn't know that it should have a dot, so it can't draw it).
So my question is how can I update the selection of a date after the setup of all dots?

Update:
This question is related to: https://github.com/Mozharovsky/CVCalendar/issues/156 but that fix doesn't seem to work.

**Comment by thomasbaldwin** [comment]
Use updated his function and got it to work. Use this code instead:

```swift
extension CVCalendarContentViewController {
    public func refreshPresentedMonth() {
        for weekV in presentedMonthView.weekViews {
            for dayView in weekV.dayViews {
                removeCircleLabel(dayView)
                dayView.preliminarySetup()
                dayView.supplementarySetup()
                dayView.dotMarkers.removeAll()
                dayView.reloadContent()
                if dayView == calendarView.coordinator.selectedDayView {
                    dayView.moveDotMarkerBack(false, coloring: false)
                }
            }
        }
    }
}
```

**Comment by KimPark89** [comment]
Thanks Thomas but this doesn't work for me. 
Also it introduces a bug: sometimes 2 selected date appears in same month.

**Comment by vishallohiamp** [comment]
Any updates on this

**Comment by thomasbaldwin** [comment]
@KimPark89 @vishallohiamp This is what I currently have:

``` swift
extension CVCalendarContentViewController {
    public func refreshPresentedMonth() {
        for weekV in presentedMonthView.weekViews {
            for dayView in weekV.dayViews {
                removeCircleLabel(dayView)
                dayView.setupDotMarker()
                dayView.preliminarySetup()
                dayView.supplementarySetup()
                dayView.topMarkerSetup()
                if dayView == calendarView.coordinator.selectedDayView {
                    dayView.moveDotMarkerBack(false, coloring: false)
                }
            }
        }
    }
}
```
