### ISSUE TITLE
Backwards-incompatible changes should have a major version bump, not just a patch.

### ISSUE THREAD

**Issue by nickmshelley** [CVCalendar/CVCalendar#199]
The latest release (1.2.8) introduced an extra parameter in `CVCalendarViewDelegate`s `didSelectDayView` method. We updated from 1.2.7 to 1.2.8 and it broke that functionality of our app because the delegate method was no longer called (the one we implemented no longer exists).

This is a code-breaking change, so that release should have been 2.0.0, or support for the old API should still be supported.

**Comment by afesteves** [comment]
Same thing happened to us.
Since `didSelectDayView` is marked as optional in the protocol, there were no compile errors.
By the time we noticed it stopped working, a lot of other changes had been made to the repository, which made pinpointing the problem take even more time.
