### ISSUE TITLE
First week of 2016 selection bug

### ISSUE THREAD

**Issue by KimPark89** [CVCalendar/CVCalendar#201]
Hi,
the auto selection mode doesn't work in the first week of 2016 (in WeekView mode).

To reproduce the bug just go to the last week of December 2015 or the second week of January 2016, then scroll to the first week of January 2016. No day will be selected.
Note: you must be in WeekView mode with shouldAutoSelectDayOnWeekChange enabled. The bug is reproducible also in the demo app.

**Comment by elsesiy** [comment]
@KimPark89 Thanks for pointing that out. We'll have a look at it :+1:

**Comment by KimPark89** [comment]
Update: the bug is not related to the first week of 2016, but to the week previous the current week.
I hope that I'll have some time to find the problem.

**Comment by elsesiy** [comment]
@KimPark89 Alright, thanks for the update. Please feel free to submit a PR :+1:
