### ISSUE TITLE
There are serious autoLayout issues with this calendar

### ISSUE THREAD

**Issue by simonmcl** [CVCalendar/CVCalendar#208]
I'm using 1.2.8 with autoLayout. The only way I can get it to work is to comment out the constraint on line 239 in CVCalendarView:

``` Swift
if !found {
    addConstraint(NSLayoutConstraint(item: self, attribute: .Height, relatedBy: .Equal, toItem: nil, attribute: .Height, multiplier: 1, constant: frame.height))
}
```

I'm placing the Calendar in a "header" section of my viewController. If I leave this line in, Xcode complains about being unable to satisfy all constraints, no matter what height / width I give the control. The result is the view and the menu are out of alignment.

The alternative is I now have to specify a fixed width for both and centre them. Which is annoying for bigger / smaller phones.

**Comment by daviskoh** [comment]
any update on autolayout support?

**Comment by elsesiy** [comment]
No no update so far, I won't have the time to fix this some time soon so if you urgently require this feature, you might be better off with alternative calendar solutions.
