### ISSUE TITLE
Inconsistent usage of custom color's

### ISSUE THREAD

**Issue by simonmcl** [CVCalendar/CVCalendar#209]
I set all of the font colour methods in the appearance delegate to the same colour, `UIColor.clearColor()`, as i'm trying to have custom UIViews / symbols for each day rather than the date (BTW your README is out of date the property has been renamed).

Only after scrolling to the next / previous month a few times does it actually take effect. Tried calling `calendarView.commitCalendarViewUpdate()` in several other places as well as `viewDidLayoutSubviews` but it didn't help.

**Comment by simonmcl** [comment]
Setting `self.calendarView.calendarAppearanceDelegate = self` before the call to `super.viewDidLoad()` in the delegate UIViewController seems to fix the issue.

**Comment by Incyc** [comment]
I encounter this too and found that setting the calendarAppearanceDelegate before setting the calendarViewDelegate works as well.

**Comment by simonmcl** [comment]
@Incyc Yeah I've seen a few comments / posts around similar issues / ideas. Sounds like the architecture / design of the code is fundamentally flawed if that is the case. It shouldn't be a requirement of a developer to set delegates in a certain order. The delegate should simply be set, and then used where it is needed. 

Looks like the developer is using the delegate property's `set` method to run some logic. The issue is probably connected to this, don't know enough about the code / have the time to dig through it.
