### ISSUE TITLE
Selected date disappears if shouldAutoSelectDayOnMonthChange is false

### ISSUE THREAD

**Issue by sprint84** [CVCalendar/CVCalendar#215]
This seems to be a bug, or I am misunderstanding the API usage.
If you set shouldAutoSelectDayOnMonthChange to false, when you scroll to the next or previous month and then come back, the previously selected date circle disappears. It seems to be selected, since I can't select the same date (that should have a circle around it), but if I select another day, it works.

While I'm here, is there a way to set the selected date to the calendar view, and not start with the current today date?

**Comment by neugartf** [comment]
Can't comment on the shouldAutoSelectDayOnMonthChange issue right now, but I agree to add the possibility to start the calendar with a custom date. We should add this as an enhancement https://github.com/Mozharovsky/CVCalendar/issues/222
