### ISSUE TITLE
Change month in weekview

### ISSUE THREAD

**Issue by EvgenyKondrashkin** [CVCalendar/CVCalendar#232]
Is it bug or feature?
If I change days in same month in weekview - just selecting another day
If I change days in different months in weekview - it animate scroll to new month, selecting first day of month - it is not right to animate scroll and autoset day(if disable autoselect not select any day) to first day of month or week(in prev month)

like so:

![Alt Text](http://i.imgur.com/beH2Lim.gif)

Will it be solved in 2.0? I make some workaround in code but it so horrible because I don't understand route, as I see there are 3 weeks that changes, but also change month - can somebody help with it? it is major for me

**Comment by gorbin** [comment]
@elsesiy can you help with it?

**Comment by elsesiy** [comment]
@EvgenyKondrashkin This is still an issue?

**Comment by EvgenyKondrashkin** [comment]
Will check it tomorrow

понедельник, 11 апреля 2016 г. пользователь Jonas-Taha El Sesiy написал:

**Comment by EvgenyKondrashkin** [comment]
Still here

![cvcalmay](https://cloud.githubusercontent.com/assets/8569176/15069107/5075824c-139d-11e6-94fc-be4ba4905352.gif)

**Comment by EvgenyKondrashkin** [comment]
@elsesiy @Mozharovsky Truly it is major bug, I try to solve it but got horrible solution - I messed up with previous, present and following weeks in CVCalendarWeekContentViewController with initialLoad and insertWeekView. As I see I solve it but create more issues. Can you check this and 243 issues?

**Comment by elsesiy** [comment]
@EvgenyKondrashkin So you want to scroll to previous/next month without autoselection of the first right?

**Comment by EvgenyKondrashkin** [comment]
No, I want to select day in weekview that contains 2 month without scroll,
like selecting days in any other weekviews. It is missbehavior scroll in
weekview and in code there us very strange data in prev, present and
following week

суббота, 7 мая 2016 г. пользователь Jonas-Taha El Sesiy написал:

**Comment by elsesiy** [comment]
@EvgenyKondrashkin No that's not true, the transition between two month is happening so there's gotta be an animated scroll. It's the same with the Apple Calendar, select a specific date and you'll be taken into the month with the respective date selected or the detail view will be presented automatically. I understand that it might be wrong to select the first of the month automatically, but the transition should be fine.

**Comment by EvgenyKondrashkin** [comment]
@elsesiy you are not right about transition between two month in weekview - I think that there should be no any transition in weekviews even in changing month. In weekview should be only one transition - user scroll or ask for current day. Like in apple calendar(ad another gif):
![icalweek](https://cloud.githubusercontent.com/assets/8569176/15138850/62455956-16b4-11e6-8ea7-f7eed848c121.gif)
there no special autoscroll transition for selecting day in next or previous month - it is userfriendly
but true in monthview there should be transition and animation, but not in weekview.

And yes there is misbehavior in selecting days - should select days that user choose, not first or current day, but it is more global problem - it happens in weekview, monthview
