### ISSUE TITLE
Limit months

### ISSUE THREAD

**Issue by drieran** [CVCalendar/CVCalendar#233]
I'm using month view. I want to limit to current and next month scrolling. How I can do it ?

**Comment by DennisH511** [comment]
Same here.  Would like to be able to limit the calendar to -1 month and +6 months of the current date/month.

**Comment by drieran** [comment]
+1

**Comment by black-lotus** [comment]
I need to set min and max date

**Comment by elsesiy** [comment]
@black-lotus A lot of user's have requested this feature already, we're working on it! Please be patient..

**Comment by borisiknowthechef** [comment]
+1
Any expectation when I will be ready?

**Comment by sochalewski** [comment]
Really need this too. Thank you in advance.

**Comment by elsesiy** [comment]
Nope no news on this one at the moment, please be patient :)

**Comment by rabehssera** [comment]
Hello

Nearly 4 months later. Has it been added yet ?

**Comment by black-lotus** [comment]
I create calendar like CVCalendar, it's not amazing like CVCalendar but it works
Feel free https://github.com/black-lotus/dnCalendar-iOS

**Comment by erolando** [comment]
I need to set min and max date

**Comment by waqar1992** [comment]
Any update on  **set min and max date**
