### ISSUE TITLE
Calendar view popping into the correct position only after a scroll

### ISSUE THREAD

**Issue by avicooper1** [CVCalendar/CVCalendar#238]
I currently have the calendar view set up with what I think are the right constraints, but the calendar view appears in the wrong position. The reason that I think the constraints are correct is because when the date or moth is changed, the calendar view "pops" to the intended position. Here are two screenshots.
<img width="376" alt="screen shot 2016-02-28 at 9 01 17 pm" src="https://cloud.githubusercontent.com/assets/11204241/13383981/b399a728-de5e-11e5-913b-523b7a87c6cd.png">
<img width="378" alt="screen shot 2016-02-28 at 9 02 27 pm" src="https://cloud.githubusercontent.com/assets/11204241/13383982/b3a7dc6c-de5e-11e5-88ce-5854a149f554.png">

One thing to note is that I do not use the month label. Instead, I display the month in the UINavigationController top bar. My question is: what methods are called when the date/month is changed, and how can I call them before the calendar view appears in order to make sure it dissent change positions while the user is interacting with it. 

Thanks for any help.

**Comment by elsesiy** [comment]
@avicooper1 Is this still an issue?

**Comment by avicooper1** [comment]
Yes, it is still an issue.
