### ISSUE TITLE
Today DotMark appeared on the top of dayview

### ISSUE THREAD

**Issue by zsmzhu** [CVCalendar/CVCalendar#240]
When add a dotmark on today, the dot will appear on the top of the dayview, only the dayview of today has this issue. It is  OK for other dayview show the dotmark and when change the calendar mode to week mode, the dot will move to bottom of today dayview like other dayview. I found this question on Demo

**Comment by gyanaprakash** [comment]
how to show dotmark on cvcalender.

**Comment by elsesiy** [comment]
@gyanaprakash Stop spamming different threads with the same question everywhere. If you need help, open up an issue and we'll have a look at it, thanks!

**Comment by gyanaprakash** [comment]
thanks i did it. very nicely.



Regard's
Gyana Prakash Gouda
 consultant, professional, service at oroprise solution
Current : +91-9844746168
Personal : +91-8895666168,   +91-8754866168
E.mail : gp.ios91@gmail.com, *gyan.prakash@oroprise.com
<gyan.prakash@oroprise.com>*

**Comment by danielbmarques** [comment]
@zsmzhu I'm having the same problem. calling `calendarView.contentController.refreshPresentedMonth()` on `viewWillAppear()` fixed it for me, but this should be fixed.

**Comment by davidpaul0880** [comment]
func shouldAutoSelectDayOnMonthChange() -> Bool {
        return false
    }
fixed for me by implementing this
