### ISSUE TITLE
setup dotmarks

### ISSUE THREAD

**Issue by rp9994** [CVCalendar/CVCalendar#250]
I want to know how add the dot marks on any specific bunch of date.

**Comment by DennisH511** [comment]
Create an array of dates you would like to have dot marks.

You can implement the following function:


`
func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {
// test to see if dayView is in your array of dates
}
`

**Comment by DennisH511** [comment]
@rp9994 
Create an array of dates you would like to have dot marks.
Implement the following delegate function with something like:
```swift
func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool {    
    // do your stuff
    let day = dayView.date.convertedDate()
    if self.myArrayOfDates.contains(date!) {
        print("date match...")
        return true
    } 
    return false
}
```
Make sure you're comparing dates without the time when you're doing your comparison test.
Have a look at the CVCalendar demo project. It's a really good starting point.

**Comment by rp9994** [comment]
Thank you Mr.DennisH511

**Comment by DennisH511** [comment]
You're welcome.

Sounds like I'm doing something very similar but I'm using this delegate function instead with pretty much the same code as before
```swift
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {

}
```

**Comment by rp9994** [comment]
if (colors!.count > 3) {
                    assert(false, "Only 3 dot markers allowed per day")
                }
Here the array of colors showing nil value
so, I am getting runtime erroor
fatal error: unexpectedly found nil while unwrapping an Optional value
in above function

The method you have  suggested supplementaryView() running errorless but the dot is not appearing on the specified date of array

**Comment by danielbmarques** [comment]
I just went through the same problem. Had to implement `dotMarker:colorOnDayView` to fix it. This should be a lot better documented, though.
