### ISSUE TITLE
CVCalendar in TableViewCell

### ISSUE THREAD

**Issue by morgan-legal** [CVCalendar/CVCalendar#254]
Hi there,

I am trying to insert a CVCalendar in a tableview cell without success. 
Since the original setup (bellow) cannot be done in a cell I do not know what to do. 

```
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    calendarView.commitCalendarViewUpdate()
    menuView.commitMenuViewUpdate()
}
```

I have tried instead (calendarView always found nil);

```
override func layoutSubviews() {
    super.layoutSubviews()
    self.calendarView.commitCalendarViewUpdate()
}
```

Does anyone has an idea of what steps I could follow to implement it?

Thanks!
Morgan

**Comment by zuaaef** [comment]
Found a solution?

**Comment by morgan-legal** [comment]
I believe I did found one. I will play around with it to see if it's fully functional and post the solution in the next couple of days.

**Comment by borisiknowthechef** [comment]
In the cell :
 override func setNeedsLayout() {
        super.setNeedsLayout()
        calendarView.layoutIfNeeded()
}

in the cellForRow:
cell.setNeedsLayout()

**Comment by MKQasim** [comment]
Please any body have query about this problem of table view  i want add selected date as an event  in table view but giving me ni value

**Comment by morgan-legal** [comment]
MKQasim, can you reformulate your question ?

**Comment by hoangtam101** [comment]
is not work well on ipad. :(

**Comment by yuanjun221** [comment]
I've found a easy way to do this. In the following implementation, the cell's height will be expand or shrink depending on the number of calenderView's rows.

In **TableViewController.swift**:

```
extension TableViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.estimatedRowHeight = 350.0
        tableView.rowHeight = UITableViewAutomaticDimension
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        if let cell = tableView.cellForRow(at: IndexPath(row: 0, section: 0)) as? CalendarTableViewCell {
            cell.menuView.commitMenuViewUpdate()
            cell.calendarView.commitCalendarViewUpdate()
        }
    }
}

extension TableViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let calendarCell = tableView.dequeueReusableCell(withIdentifier: "CalendarCell", for: indexPath) as! CalendarTableViewCell
        calendarCell.tableView = tableView
        return calendarCell
    }
}
```

In CalendarTableViewCell.swift:
```
class CalendarTableViewCell: UITableViewCell {
    
    @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!
    
    var tableView: UITableView!
}


extension CalendarTableViewCell {
    
    override func awakeFromNib() {
        super.awakeFromNib()
        
        menuView.menuViewDelegate = self
        calendarView.calendarDelegate = self
    }
    
    override func layoutIfNeeded() {
        super.layoutIfNeeded()
        
        tableView.beginUpdates()
        tableView.endUpdates()
    }
}


extension CalendarTableViewCell: CVCalendarMenuViewDelegate {
    
}


extension CalendarTableViewCell: CVCalendarViewDelegate {
    
    func presentationMode() -> CalendarMode {
        return .monthView
    }
    
    func firstWeekday() -> Weekday {
        return .sunday
    }
}
```
In **Main.Storyboard**:
1. add a height constraint for the calendar view.
2. add constraint form calendarView.Bottom to ContentView.Bottom and **make its priority to 999**.

Demo project please check [here](https://github.com/yuanjun221/CVCalendarInCellDemo.git).

**Comment by hoangtam101** [comment]
hi yuanjun221: thank you so much.

**Comment by a8b** [comment]
@yuanjun221 solution doesn't work if you need custom appearance (fonts and colors). Calendar view shows default appearance for first 2 months, applying customizations starting from 3rd swipe only.
