### ISSUE TITLE
Coding style standards

### ISSUE THREAD

**Issue by dbmrq** [CVCalendar/CVCalendar#262]
I'm starting to work on this code and I think there are a number of coding style issues that could be improved.
Since my OCD won't allow me to let this be I'm already changing some things for myself, I'll make a PR for your consideration, but these are not my decisions to make, so I think it would be good to agree upon some standards for CVCalendar's code.

Here's what I propose:

**Variable names should always start with a lowercase letter.**
In the `CVCalendarContentViewController`, for instance we have:

``` swift
public let Previous = "Previous"
public let Presented = "Presented"
public let Following = "Following"
```

**Swift constructors should be preferred over legacy constructors.**
In the same file we have `CGSizeMake()` instead of `CGSize()`.

I think it's standard practice in swift to **start `else` statements right after the closing `if` bracket**, but the code here is not consistent about that, still in the same file we have:

``` swift
if each is UILabel {
    continue
}
else if each is CVAuxiliaryView {
    continue
}
else {
    each.removeFromSuperview()
}
```

**Control statements shouldn't be wrapped in parentheses** unnecessarily, like so:

``` swift
if (frame.width > 0) {
    preliminarySetup()
    supplementarySetup()
}
```

I think it would be good to define a **maximum line length**; I suggest 100 characters.

**`guard let` should be preferred over `if let` for large blocks** (> 5 lines?).

**Binary operators should always be surrounded by spaces** (`2 + 2 = 4` instead of `2+2=4`).

**Prefer `!array.isEmpty` over `array.count > 0`.**

I think it would be a good idea to use [SwiftLint](https://github.com/realm/SwiftLint) and chose which rules to implement.

**Comment by elsesiy** [comment]
@danielbmarques Great remark! From what I've seen so far, you seem to be a really good fit for our project. Do you want to work with us?

**Comment by danielbmarques** [comment]
@elsesiy Well, usually I don't have as much free time as I had these last days, so I might be a little absent, but if thats ok, sure, it would be an honor. :)

**Comment by elsesiy** [comment]
@danielbmarques Please give me your email address so I can add you to our team slack for communication purposes ;)

**Comment by danielbmarques** [comment]
@elsesiy danielbmarques at gmail dot com
Thanks. :)
