### ISSUE TITLE
typealiases too broad

### ISSUE THREAD

**Issue by dbmrq** [CVCalendar/CVCalendar#264]
I think it's a very bad choice to have such broad typealiases as `Date`.
Since pretty much all CVCalendar users are working with dates, it's likely that some of them (like me) will create their own `Date` class, which will conflict with CVCalendar's if its classes are added directly to the project.
It wouldn't be hard to replace all relevant occurrences of "Date" with "CVDate", for instance, and I think that would be a much better choice. The same goes "Weekday". I can do this and make a PR if there are no objections.

**Comment by elsesiy** [comment]
@danielbmarques No objection from my side. What about you guys? @neugartf @Mozharovsky

**Comment by neugartf** [comment]
Sounds good to me

**Comment by danielbmarques** [comment]
Ok, I made a PR. I added the CV prefix to `Date`, `Weekday` and `Delegate`. I think ideally this prefix should be added to all typealiases in CVCalendarView.swift, but some of those would be breaking changes, so I tried to change as little as possible.

Oh! **Now I just realized changing `Weekday` to `CVWeekday` breaks the `firstWeekday() -> Weekday` function**, all users would have to update that to `CVWeekday`… so it might be better to wait this when there are other breaking changes (maybe version 2). Anyway, now I already made the PR, so I'll leave it there… you guys can close it if you think it's best for now.

**Comment by neugartf** [comment]
We think it's better to put it in the version 2 branch. Feel free to issue another one. Otherwise I'll create one later that day

**Comment by elsesiy** [comment]
@danielbmarques I totally agree with you that this is a breaking change and shouldn't be included in minor releases. Another possibility to what @neugartf has mentioned would be releasing 1.3.0 prior to your PR and 1.4.0 afterwars. 
@Mozharovsky What's your opinion on this?

**Comment by elsesiy** [comment]
`Date` has been renamed to `CVDate` a long time ago which solves this issue for now. Weekday is not a Foundation class and Delegate should be fine too.
