### ISSUE TITLE
Current date dotmaker appear on top of DayView.

### ISSUE THREAD

**Issue by rp9994** [CVCalendar/CVCalendar#266]
I'm having problem in dotmaker, that Current date dotmaker appears on top of the dayview, whereas other than current date dotmaker is appearing at bottom of dayview.
so, I want current date dotmaker also appear at bottom of the dayview.

**Comment by danielbmarques** [comment]
I have the same problem here. It looks like it completely ignores the dot marker offset for the current day. I tried this and it didn't change a thing:

```swift
func dotMarker(moveOffsetOnDayView dayView: DayView) -> CGFloat {
    if dayView.date.convertedDate()?.startOfDay() == NSDate().startOfDay() {
        return -11 // I also tried returning all sorts of different things here.
    }
    return 11
}
```

Calling `calendarView.contentController.refreshPresentedMonth()` on `viewWillAppear()` worked a couple of days ago, but now it doesn't anymore, I'm not sure why… maybe I changed something else.

**Comment by danielbmarques** [comment]
I just ran my code again without changing a thing and it worked properly, so I think `refreshPresentedMonth` might have nothing to do with it after all, it could have been just a coincidence that it started working after I added that. For now I can't figure out how to reproduce this bug consistently, it seems to happen at random.

**Comment by danielbmarques** [comment]
Ok, calling `calendarView.contentController.refreshPresentedMonth()` on `viewDidLayoutSubviews()` fixed the problem, except that the current day dot doesn't show at all until the user deselects the current day. It's still better than the dot showing on top, though. 
@rp9994, let us know if that works for you. I'll try to track down the root of the problem when I have more time.

**Comment by rp9994** [comment]
@danielbmarques calling calendarView.contentController.refreshPresentedMonth() on viewDidLayoutSubviews() fixed the issue. 

Thank you! :)

**Comment by rp9994** [comment]
but at first time when view is load a dot on current date doesn't appear. If I click any other date then dot comes up! 

Although, that's a minor issue, can be compromised!

again thanks!

**Comment by artekr** [comment]
@rp9994 It actually shows the dot on current date. it's just the dot has the same colour as the currently highlighted background colour (red). It you change the default dot colour to some other ones, you will see the dot. 
But the weird thing is if you click any other date then click on the current date again, the dot become white again.

But thanks for the solution though, it's still much better than show on the top :)

**Comment by daichi1021** [comment]
CVCalendarDayView.swift
setupDotMarker()　method
`insertSubview(dotMarker, atIndex: 0)`
change
`addSubview(dotMarker)`

**Comment by chanonly123** [comment]
Not working

**Comment by ccortessanchez** [comment]
I believe this method fixes the problem with dot marker moving up and down if the day is selected

`func dotMarker(shouldMoveOnHighlightingOnDayView dayView: DayView) -> Bool {
        return false
}`

**Comment by TungWang** [comment]
> @rp9994 It actually shows the dot on current date. it's just the dot has the same colour as the currently highlighted background colour (red). It you change the default dot colour to some other ones, you will see the dot.
> But the weird thing is if you click any other date then click on the current date again, the dot become white again.
> 
> But thanks for the solution though, it's still much better than show on the top :)

Hello!
I am facing the problem of dot become white.
Do you have any solution of this?
