### ISSUE TITLE
crashing on previous and Next button

### ISSUE THREAD

**Issue by rv928** [CVCalendar/CVCalendar#272]
Hi,
    I am using this method to add circle on specific date but it is crashing on previous and next button click while fetching dayView.date in this method

func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {

```
    print("dayView.date.date, \(dayView.date.date)")
    print("dayView.date, \(dayView.date)")


return false
```

}

**Comment by elsesiy** [comment]
@rv928 What's your setup like? What do you try to achieve? Please elaborate on these questions, otherwise we're not able to provide any help.

**Comment by henrygould** [comment]
Not sure if you're running into the same thing, but when you switch months, there is a period of time when interacting with the dayView objects where .date is null. It doesn't get populated until init. My issue for example is I'm trying to display circles for certain dates, but .date isn't always available when this code executes:

![image](https://cloud.githubusercontent.com/assets/17415106/14962928/ed1831ec-1066-11e6-927b-dc40e49df92d.png)
