### ISSUE TITLE
How do I call methods on viewWillAppear? (E.g. shouldShowOnDayView, colorOnDayView, moveOffsetOnDayView)

### ISSUE THREAD

**Issue by rp9994** [CVCalendar/CVCalendar#273]
I want to call following methods on viewWillAppear

func dotMarker(shouldShowOnDayView dayView: CVCalendarDayView) -> Bool 
func dotMarker(colorOnDayView dayView: DayView) -> [UIColor]
func dotMarker(moveOffsetOnDayView dayView: DayView) -> CGFloat

because when data is updated I want a dot appear on than that or if data is deleted then dot should be disappear, so that can be possible in viewWillAppear() according my project!

**Comment by patchthecode** [comment]
Have you found a solution to this?
