### ISSUE TITLE
Store selected days and then display them

### ISSUE THREAD

**Issue by antonijap** [CVCalendar/CVCalendar#274]
I am new to this calendar so my apologies if this is already answered. I tried to find a similar question but never found one.

I am trying to make a menstrual diary with your calendar and i don't know how should I store and display selected dates.

I made array od DayViews
`var selectedDays = [DayView]()`
when I do:

```
func didSelectDayView(dayView: CVCalendarDayView, animationDidFinish: Bool) {
        selectedDays.append(dayView)

        for day in selectedDays {
            selectedDay = day
        }
    }
```

Nothing really happens. Can somebody help me a little to find my way in this awesome calendar?

**Comment by elsesiy** [comment]
@antonijap Sounds like an interesting app you're working on :+1: I assume you just want to store the underlying dates that have been selected right? I'd rather create an Array of NSDates and for each dayView selected add the corresponding date to the array, so quite similar to your proposition. Could you elaborate on the issue?

**Comment by antonijap** [comment]
Well,I have an array of NSDates and I wonder is there some function to display them when Calendar loads?
