### ISSUE TITLE
show dots from an array of NSDate

### ISSUE THREAD

**Issue by alessandrocatoni** [CVCalendar/CVCalendar#279]
Hi!
First of all, I wanted to congratulate you for you great CVCalendar !
I'm trying to extract NSDate from an array and use this to show dots in Calendar. But since i'm new in swift development i don't know how!
Can you help me?

**Comment by zuaaef** [comment]
still need help?

**Comment by alessandrocatoni** [comment]
Hi! 
Absolutely yes 😂

Inviato da iPhone

**Comment by zuaaef** [comment]
oh. i thought you solved it. I was stuck here too. xD

**Comment by alessandrocatoni** [comment]
😂😂 ok 

Inviato da iPhone

**Comment by ridvank** [comment]
I suppose that you have an array of NSDate. So you should update your calendar in this way:
```
var dotArray = [NSDate]() {
        didSet{
            self.viewCalendar?.contentController.refreshPresentedMonth()
        }
    }
```

**Comment by kiranvgowda** [comment]
Hi,

First of all thanks for this awesome calendar.

How to avoid the selection of dates in previous or next month / not to show the markers.

I am giving dates as input from array.
 but the issue is it is showing dot markers for those dates in all the months.
How to solve this?

Thanks in advance.
