### ISSUE TITLE
Saving CircleView via NSUserDefault to keep the same days highlighted when app opens

### ISSUE THREAD

**Issue by abdul123455** [CVCalendar/CVCalendar#280]
I am trying to save the days that get highlighted, so when the user re-opens the app the previous days are still highlighted.

 func preliminaryView(viewOnDayView dayView: CVCalendarDayView) -> UIView {
        let circleView = CVAuxiliaryView(dayView: dayView, rect: dayView.bounds, shape: CVShape.Circle)
        circleView.fillColor = .colorFromCode(0x99FF33)

```
    return circleView
}

func preliminaryView(shouldDisplayOnDayView dayView: CVCalendarDayView) -> Bool {

    if (dayView.isCurrentDay)   {

           return true}

   return  false

}
```

**Comment by nikolay-dementiev** [comment]
Hello.

Tell more about your problem. You have a problem in your local project or you want that "CVCalendar" will have some feature?
