### ISSUE TITLE
Help put the blue circles to this day

### ISSUE THREAD

**Issue by schulz89sp** [CVCalendar/CVCalendar#282]
Hello everyone, I need to put the blue circles when I insert an event in a day ... what code / method should I use?
In addition I would like to take away everything that puts as an example of default ...
Thank you!

**Comment by henrygould** [comment]
supplementarySetup() populates the circles.

supplementaryView(ShouldDisplayOnDayView) determines whether a circle displays. You should see in there the randomizing function that does the example defaulting.

**Comment by schulz89sp** [comment]
I found the function that puts the blue circles in the case because it is this:
if (Int (arc4random_uniform (3)) == 1)
But having a table under the calendar I would like that if you have an entry in the table then it must be put on blue circle otherwise not ... how can I?

**Comment by henrygould** [comment]
You could put your logic in supplementaryView and that way it would return true if it's supposed to display the circle and return false if it's not supposed to. Since you're working with a dayView object, you have access to the date from there and can check that against your table, assuming your table is a table of dates.

**Comment by schulz89sp** [comment]
Meanwhile, thanks for the answers ...
In function: supplementaryView (shouldDisplayOnDayView dayview: DayView) I put a "IF" that compares when "dayView.date.commonDescription = date" (the date is my String) ..
If you do so the blue circles are seen properly ... BUT why if I print "dayView.date.commonDescription" he writes dates of the current month, the previous month and the following month but not update if I change the month?
By doing so if I go back to two months I delete circles facts and the app sends me crash because he tells me that he dayView.date.commonDescription as "nil" value?
I hope I explained ... Thanks again!

**Comment by henrygould** [comment]
I think you're probably running into this case:

https://github.com/Mozharovsky/CVCalendar/issues/272

Implementing my solution suggested there should help.

**Comment by schulz89sp** [comment]
Ok now not going the crash.
But the problem of the circles disappear remained! :(
So ... if the function "supplementaryView (shouldDisplayOnDayView dayview: DayView)" I do "print (dayView.date.commonDescription)" in the console I find the dates ranging from "March 28, 2016 al June 5, 2016" so if I go over in type months to February, when returning the current month (May) the circle that was on yesterday for example, has disappeared! although within it there are events ...

**Comment by schulz89sp** [comment]
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
    let dateformatter = NSDateFormatter()
    dateformatter.dateFormat = "yyyy/MM/dd"
    let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)
    let date_Array = ["2016/02/10","2016/02/11","2016/02/12"]
    print(dataOdierna) <-- print: 2016/03/28 .... 2016/06/05
    for(var i=0;i<date_Array.count;i++)
    {
        if(date2==date_Array[i])
        {
            return true
        }
    }
    return false
}

**Comment by schulz89sp** [comment]
Stops everything !!!
Excuse my fault ... I was wrong to pass the value to compare ... if I was going back or forward to two months the date was lost ...
I am a BIPPPPP :)
I always close my questions anyway then ...
I had downloaded the version of Branch: master, and if I put the iPhone in landscape calendar skips constrait ... there is a way to solve?
Thank you :)
