### ISSUE TITLE
calendarView.toggleViewWithDate has no effect if shouldAutoSelectDayOnMonthChange implements with return false

### ISSUE THREAD

**Issue by ylybbs** [CVCalendar/CVCalendar#286]
if my calendarView delegate implements method with
    func shouldAutoSelectDayOnMonthChange() -> Bool {
        return false
    }
when we call calendarView.toggleViewWithDate(date: ),if presentMonthView has no selected day,it do nothing

**Comment by srinivasanVaradan** [comment]
If i return false for ShouldAutoSelectDayOnMonthChange() method , i won't allow to change view mode . if i currently in month view try to change to WeekView won't happen

**Comment by k28gupta** [comment]
CalendarView doest not retain its selected date on Mode change, if shouldAutoSelectDayOnMonthChange() && shouldAutoSelectDayOnWeekChange() are returning false. This should not be the case.

This methods seem to be a flag for automatically selecting a date on next/previous month/week, while I am having issue with retaining their already selected date on Mode change (like MonthView to WeekView and vice versa).
