### ISSUE TITLE
I want to display TableView on supplementaryView for every day to list down events.

### ISSUE THREAD

**Issue by priyankagaikwad** [CVCalendar/CVCalendar#289]
I want to display TableView on supplementaryView for every day to list down events.
Tried the following code
    func supplementaryView(viewOnDayView dayView: DayView) -> UIView {
        tableView.frame  =   CGRectMake(0, 0, 150, 100);
        tableView.registerClass(UITableViewCell.self, forCellReuseIdentifier: "cell")
        return tableView
    }
but doesn't worked well

**Comment by MKQasim** [comment]
i have the same  issue table view does'nt access the day and how i list down the events !
