### ISSUE TITLE
func dotMarker(sizeOnDayView dayView: DayView) -> CGFloat is not called

### ISSUE THREAD

**Issue by daviskoh** [CVCalendar/CVCalendar#313]
It seems that `func dotMarker(sizeOnDayView dayView: DayView) -> CGFloat` is not being called. The proper delegate is set and the other methods are correctly being called as shown by what is printed out.

![image](https://cloud.githubusercontent.com/assets/5395403/16434255/c38fbfac-3d5c-11e6-8f80-fb8c01b7e2c2.png)

![image](https://cloud.githubusercontent.com/assets/5395403/16434037/58ce1c14-3d5b-11e6-83f1-c1b9b0d659bc.png)

It seems that `func dotMarker(colorOnDayView dayView: DayView) -> [UIColor]` and `func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool` are required as omitting the 1st throws an [error](https://github.com/Mozharovsky/CVCalendar/issues/173) while omitting the latter will prevent `func dotMarker(sizeOnDayView dayView: DayView) -> CGFloat` from being called.

Also, implementing all 3 methods adds dot markers on every DayView. Not sure if that is the intended behavior...

![image](https://cloud.githubusercontent.com/assets/5395403/16434210/6b1cd724-3d5c-11e6-88ae-64f682ff5593.png)

It looks like this [line](https://github.com/Mozharovsky/CVCalendar/blob/ce4d38121a586c13f4d266b2f371da0fdcad9ca4/CVCalendar/CVCalendarDayView.swift#L254) is the culprit
## Your Environment

Xcode 7.3.1
Swift 2.2
CVCalendar 1.2.9

**Comment by elsesiy** [comment]
@daviskoh Thanks for pointing this out. Unfortunately I won't have the time to look into it, so if you find a reasonable solution to it please submit a PR so other can benefit from it! Kind regards.

**Comment by SalahEddin** [comment]
I'm having the same issue, same environment as well

**Comment by rabehssera** [comment]
Well, by default,  dotMarker(shouldShowOnDayView dayView: DayView) -> Bool returns false. So, the dots are never set.
When the dots are shown, you have to set their color and their size (because it doesn't have a default function for the color).
