### ISSUE TITLE
Present weekday font does not change

### ISSUE THREAD

**Issue by Abhinav93** [CVCalendar/CVCalendar#351]
Present(current) weekday font does not change after implementing the delegate-
    func dayLabelPresentWeekdayFont() -> UIFont {
    }

**Comment by alickbass** [comment]
I had this issue as well... Try setting `calendarAppearanceDelegate` before any other delegate. This super weird and unreliable

**Comment by kalmurzayev** [comment]
Can confirm @alickbass solution. That is indeed really strange, but setting `calendarAppearanceDelegate` before any other delegate helped fixing all fonts.
