### ISSUE TITLE
Prevent scrolling between weeks or months

### ISSUE THREAD

**Issue by wgsomerville** [CVCalendar/CVCalendar#36]
I'm working on an app that just needs to display one specific week.  I've loved working with CVCalendar, but am wondering if there is a way to prevent users from scrolling between the next/previous week without heavily modifying the scrollview implementation.

Thanks again for making this @Mozharovsky!

**Comment by Mozharovsky** [comment]
Hello @wgsomerville, 

Thank you for using this software. 

After the upcoming release I'll add a way to disable scrolling between views. 

Regards, 
Eugene

**Comment by wgsomerville** [comment]
Fantastic! Thanks so much for the reply.

**Comment by Charlesleonius** [comment]
Did this ever happen?

**Comment by wgsomerville** [comment]
It hadn't last time I used CVCalendar, but if I remember correctly (its been a while), I think I ended up removing the gesture recognizer (maybe the pan gesture recognizer?) or something to prevent unneeded scrolling.  It was a bit of a hack but it worked.

**Comment by Charlesleonius** [comment]
Yeah I ended up just disabled the scroll view. Thanks for the reply though!

**Comment by elsesiy** [comment]
Great you found a solution --> closed.
