### ISSUE TITLE
CVDate equatable?

### ISSUE THREAD

**Issue by popodidi** [CVCalendar/CVCalendar#370]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.
## Expected Behavior

Two `CVDate` objects should be equal to each other if the `year`, `month` and `day` are all the same.
## Current Behavior

Two `CVDate` objects seem to be equal to each other as they share the same memory access.
## Possible Solution

Since `CVDate` subclasses the `NSObject`, overriding `func isEqual` should solve this problem.

```
override func isEqual(object: AnyObject?) -> Bool {
    if let date = object as? CVDate {
        return self.year == date.year &&  self.month == date.month &&  self.day == date.day
    }
    return false
}
```

I'm not sure if it is possible to implement `Equatable` protocol as subclassing `NSObject`. If possible, this should solve the problem.

```
func == (lhs: CVDate, rhs: CVDate) -> Bool{
    return lhs.year == rhs.year &&  lhs.month == rhs.month &&  lhs.day == rhs.day
}
```

If you want to keep the `NSObject` equatability, a new comparing function should work as well

```
func equalsTo(date: CVDate) -> Bool{
    return self.year == date.year &&  self.month == date.month &&  self.day == date.day
}
```
## Steps to Reproduce (for bugs)

``` swift
let date_1 = CVDate(date: NSDate())
let convertedDate_1 = date_1.convertedDate()!
let date_2 = CVDate(date: convertedDate_1)

print(date_1 == date_2) // This returns false as I except to be true
```
## Context

I was using an array `var markerDates: [CVDate]` of `CVDate` to save the data of `dotMarker`s and passing the array through different `viewController`s. I implemented the function as below

``` swift
func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool {
    return markerDates.contains(dayView.date)
}
```

It didn't work until I fixed it by custom predicate

``` swift
func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool {
    return markerDates.contains({
        return $0.year == dayView.date.year &&  $0.month == dayView.date.month &&  $0.day == dayView.date.day
    })
}
```
## Your Environment
- Version used : 1.3.1
- Device used : iPhone 6
- Physical device : y

**Comment by elsesiy** [comment]
@popodidi Thanks for reporting, I'll look into that.

**Comment by CarlosJJR** [comment]
@popodidi so far this issue is still happening. I was implementing a similar functionality and had the same problem. If you use `Date` instead of `CVDate` then it should work. Something like this:

```
func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool {
    return markerDates.contains(dayView.date.convertedDate()!)
}
```
