### ISSUE TITLE
Update example to use dayView.frame instead of bounds for preliminaryView (ERROR)

### ISSUE THREAD

**Issue by schulz89sp** [CVCalendar/CVCalendar#371]
- [Y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y] I have verified that I am using the latest version of CVCalendar.
- [Y] I have given my issue a non-generic title.
## Expected Behavior

If you modify:
let circleView = CVAuxiliaryView(dayView: dayView, rect: dayView.bounds, shape: CVShape.circle)
With:
let circleView = CVAuxiliaryView(dayView: dayView, rect: dayView.frame, shape: CVShape.circle)

The circle is not created on today's date, but two days later ...
If I leave "dayView.bounds" even with the updated version of CVCalendar then no problem
## Possible Solution

Leave "dayView.bounds" then no problem

Help me?

**Comment by schulz89sp** [comment]
public func preliminarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.preliminaryView?(shouldDisplayOnDayView: self) , shouldShow {
                if let preView = delegate.preliminaryView?(viewOnDayView: self) {
                    preliminaryView?.removeFromSuperview()
                    preliminaryView = preView
                    weekView.insertSubview(preView, at: 0)
                    preView.layer.zPosition = CGFloat(-MAXFLOAT)
                }
        }
        else {
            preliminaryView?.removeFromSuperview()
        }
    }

    public func supplementarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.supplementaryView?(shouldDisplayOnDayView: self) ,
            shouldShow {
                if let supView = delegate.supplementaryView?(viewOnDayView: self) {
                    weekView.insertSubview(supView, at: 0)
                }
}

weekView.insertSubview(supView, at: 0) In supplementarySetup I take off "week View" and leave only "insertSubview (preview, at: 0)" otherwise the blue circles are only at the first day of the week and not the correct date

**Comment by elsesiy** [comment]
@schulz89sp Is this still an issue with the latest master?
