### ISSUE TITLE
toggleCurrentDayView doesn't work

### ISSUE THREAD

**Issue by CapslockCruiser** [CVCalendar/CVCalendar#381]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior

I believe calling this method should bring to focus the current month; however, it stays the same.

**Comment by elsesiy** [comment]
@CapslockCruiser Thank you for reporting this issue. I'll validate it and provide a fix if I find the time.

**Comment by justinctlam** [comment]
@CapslockCruiser are you able to repro this in the demo? Can you provide repro steps?

**Comment by elsesiy** [comment]
Can't reproduce this and it's been three months thus closed.
