### ISSUE TITLE
Range select and scroll the view for next month -> view greyed out  

### ISSUE THREAD

**Issue by SandeepCoder** [CVCalendar/CVCalendar#407]
I am facing an issue while selecting the date range for the different month. Below is the scenario:

1. Return the true for 'shouldSelectRange()' delegate
2. Select any first date
3. Now try scrolling the view for next month 
4. The whole view is grayed out and can not restore the original normal view

Please have a look into the issue
![simulator screen shot 20-dec-2016 1 03 05 pm](https://cloud.githubusercontent.com/assets/7877700/21341853/ac361e28-c6b4-11e6-9533-a4e4f52e4b67.png)

**Comment by stshelton** [comment]
any update on this having this same issue??

**Comment by elsesiy** [comment]
@stshelton No updates so far, don't know when I'll be having the time to look into it.

**Comment by stshelton** [comment]
Actually just got it to work!  If you specify the max range in the  'maxSelectableRange()' method in the delegate, Your range selected will stay on the correct month even if ur end date ends in the next month.  Without the 'maxSelectableRange()' set you should recreate this bug

**Comment by RSickenberg** [comment]
I have the same issue.

**Comment by Sandeep-Appster** [comment]
I am not pretty much sure if there is any other complication but commenting below code in disableDays method in CVCalendarDayViewControlCoordinator.swift class solves the issue.


-        let calendar = self.calendarView.delegate?.calendar?() ?? Calendar.current
Add a comment to this line
-        monthView.mapDayViews { dayView in
-            guard let currDate = dayView.date.convertedDate(calendar: calendar) else {
-                return
-            }
-            
-            if let earliestDate = calendarView.earliestSelectableDate,
-                currDate.compare(earliestDate) == .orderedAscending {
-                disableUserInteraction(for: dayView)
-                return
-            }
-            
-            if let beforeDate = beforeDate,
-                currDate.compare(beforeDate) == .orderedAscending {
-                disableUserInteraction(for: dayView)
-                return
-            }
-            
-            if let afterDate = afterDate,
-                currDate.compare(afterDate) == .orderedDescending || currDate.compare(afterDate) == .orderedSame {
-                disableUserInteraction(for: dayView)
-                return
-            }
-            
-            if let latestDate = calendarView.latestSelectableDate,
-                currDate.compare(latestDate) == .orderedDescending {
-                disableUserInteraction(for: dayView)
-                return
-            }
-        }

**Comment by elsesiy** [comment]
@Sandeep-Appster Please use proper code formatting on your comment.

**Comment by Sandeep-Appster** [comment]
edited.

**Comment by elsesiy** [comment]
@Sandeep-Appster Please check with the latest version of this library and report back, thanks

**Comment by rohitpradhan** [comment]
> Actually just got it to work! If you specify the max range in the 'maxSelectableRange()' method in the delegate, Your range selected will stay on the correct month even if ur end date ends in the next month. Without the 'maxSelectableRange()' set you should recreate this bug

What should be the value of range?

**Comment by justdan0227** [comment]
Did this ever get fixed?  I have a selection button that I can turn on and if I select a range and then turn off the select range 

func shouldSelectRange() -> Bool {
        return selectRangeFlag
    }

if I turn it back off, I can no longer select any date before the selected range
