### ISSUE TITLE
Select dayOut and change month

### ISSUE THREAD

**Issue by schulz89sp** [CVCalendar/CVCalendar#419]
- [ X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X ] I have verified that I am using the latest version of CVCalendar.
- [X ] I have given my issue a non-generic title.

## Expected Behavior
The calendar should show in blue the day I selected from precendete month, not the first of the month to leaving aside.

## Current Behavior
If you select the month of January for example, just hold on February 3 on days out, the month is changed and the press console "Selected Feb. 3" but then immediately switches to the "Selected February 1", why?
If I change the month scrolling on the screen in blue selected day is the first day of the month, but if I press the "3", when it changes month, the calendar must have selected the day "3" in blue is not the first of the month? I am wrong?

## Possible Solution
I have no idea

## Steps to Reproduce
1.  Take the month of January and premium on February 3 that is a day out;
2.  The console will print on screen: "Selected February 3";
3.  Will be shown just the month of February, the console will print: "Selected Feb. 1" and selected in blue day on the calendar will be February 1 and not 3 as selected from the previous month.

**Comment by elsesiy** [comment]
Please look at the delegate method `shouldAutoSelectDayOnMonthChange()` to change this behavior.
