### ISSUE TITLE
Pods not updated

### ISSUE THREAD

**Issue by slehyder** [CVCalendar/CVCalendar#420]
Good thing I wanted to tell you that the pods in this library are not updated and there are functionalities that fail. (Eye only on the pods), since manually adding it works perfect.

If you could review this or someone can clarify why this happens.

**Comment by Paulo-Branco** [comment]
I second that. A new pod release would be nice. I could really use those new range delegate methods but I can't have my podfile tied directly to the git repo.

**Comment by elsesiy** [comment]
@slehyder @Paulo-Branco I might be able to do a release within this week. As nobody, especially @Mozharovsky isn't working on this project anymore, this will be my last release too.

**Comment by Paulo-Branco** [comment]
Will there be anyone left to support it? We're using it on a production app right now. It's not completely irreplaceable, but it's probably one of the best of its kind, and it would be a shame to let it go to waste.

**Comment by elsesiy** [comment]
@Paulo-Branco Believe me, I've pictured the story also differently. I've put a lot of time and effort into my contribution and asked the owner already about changing ownership but he isn't responding at all. The only solution would be a fork but I'm not sure I want to continue that way...So to answer your question properly: I don't know.

**Comment by Paulo-Branco** [comment]
Well... If you choose to fork it to continue its development, let me know. I'll pitch in anytime I can.

**Comment by elsesiy** [comment]
@Paulo-Branco As you might've noticed, we moved the repository to an organization. If you want to join me to work on the project I'd be glad to invite you to!

**Comment by Paulo-Branco** [comment]
That would be great. I'll see if I can pitch in from time to time to tackle a few issues : )

**Comment by elsesiy** [comment]
@Paulo-Branco I just invited you.

**Comment by elsesiy** [comment]
Just published a new release, see https://github.com/CVCalendar/CVCalendar/commit/cc932a89c20dc025b40ed4047b3ece0044857731
