### ISSUE TITLE
Method preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool works incorrect.

### ISSUE THREAD

**Issue by MrAshy** [CVCalendar/CVCalendar#425]
- [+] I have verified there are no duplicate active or recent bugs, questions, or requests
- [+] I have verified that I am using the latest version of CVCalendar.
- [+] I have given my issue a non-generic title.

## Expected Behavior
I need that all dayView have circleView and in method i return always true.

## Current Behavior
CircleView sets ONLY on monday days.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):
Version 1.4.1

**Comment by elsesiy** [comment]
Please use the latest version and report a new issue, if the problem still exists. Thanks!
