### ISSUE TITLE
CalendarView leaking memory

### ISSUE THREAD

**Issue by jjjeeerrr111** [CVCalendar/CVCalendar#427]
The CalendarView object is leaking memory during scrolling. Specifically the CVCalendarMonthContentViewController is creating new scrollViews and new calendarViews when user scrolls through the calendar (month by month)

<img width="919" alt="screen shot 2017-02-17 at 9 48 00 am" src="https://cloud.githubusercontent.com/assets/7354919/23069637/31966e00-f4f6-11e6-947a-8f42cd6bca4e.png">

**Comment by elsesiy** [comment]
@jjjeeerrr111 Thank you, I'll need to look into that in more detail..

**Comment by elsesiy** [comment]
I can't reproduce this with the latest master. Can you please test it again?
