### ISSUE TITLE
func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool  “ this Method  in ios 10 Can display normally 。but is ios 9 can't display normally. and use “Debug view hierarchy” can see the dotmark.why???

### ISSUE THREAD

**Issue by inkCrazy** [CVCalendar/CVCalendar#429]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior

dotmarker show in any  type device that i setup.
## Current Behavior

dotmarker show in ios 10 . * ,not show in ios 9 . *
the picture is follow:
in ios 9.*
![image](https://cloud.githubusercontent.com/assets/12253453/23246997/689f95a8-f9d2-11e6-8784-c87e8843cc58.png)
in ios 10.*
![image](https://cloud.githubusercontent.com/assets/12253453/23247013/7ce5868a-f9d2-11e6-8189-abb408bb3d56.png)
xcode Debug view hierarchy
![image](https://cloud.githubusercontent.com/assets/12253453/23247005/70024dea-f9d2-11e6-8271-a5cc1688cb90.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Device used i.e. iPhone 6S plus
swift3.0
Xcode8.2.1
iOS9.3.5/iOS 10
'CVCalendar', '~> 1.4.1'

**Comment by radenfazlur** [comment]
Any update on this issues?
