### ISSUE TITLE
i want to  setup selected day/today/other unselected day's  text color and backroundcolor

### ISSUE THREAD

**Issue by inkCrazy** [CVCalendar/CVCalendar#430]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior

i want to this 
today always is :textColor:white  backgroundColor:blue  
selected day always is :  textColor : red  backgroundColor : white
![image](https://cloud.githubusercontent.com/assets/12253453/23248269/71b5327c-f9d9-11e6-9e98-75e27954487e.png)

## Steps to Reproduce (for bugs)

i don't Understand this attribute：－－－－－ CVStatus  point  Which states
@objc public enum CVStatus: Int {
    case `in`, out, disabled, selected, highlighted
}

i use these methods

    func dayLabelPresentWeekdayTextColor() -> UIColor {
        return UIColor.red
    }
    
    func dayLabelPresentWeekdaySelectedBackgroundColor() -> UIColor {
        return UIColo.red
    }
    
    
    func dayLabelWeekdaySelectedTextColor() -> UIColor {
        return UIColor.white
    }
    func dayLabelWeekdaySelectedBackgroundColor() -> UIColor {
        return UIColor.blue
    }
Result is ：

selected other day :textcolor->white  /backgroundColor:blue
 current day:textcolor->red  /backgroundColor:red   
unseleted day : textcolor->black  /backgroundColor : white

![image](https://cloud.githubusercontent.com/assets/12253453/23248319/bc9b58ac-f9d9-11e6-8ce2-9061fe906bdd.png)

selected current day: 
selected current day :textColor:white /backgroundColor:red  
other day : textColor:black /backgroundColor : white
![image](https://cloud.githubusercontent.com/assets/12253453/23248153/dc972cc2-f9d8-11e6-82a3-5b51e283099d.png)

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by aloveric** [comment]
How to add dot under day number if had task?

**Comment by RSickenberg** [comment]
Same issue
