### ISSUE TITLE
How do I jump to the next year?

### ISSUE THREAD

**Issue by kutakmir** [CVCalendar/CVCalendar#431]
## Expected Behavior
There is a method to jump to a next / previous year.

## Current Behavior
There is no method to jump to a next / previous year.

## Possible Solution
Implement it.

## Steps to Reproduce (for bugs)
Open CVCalendarView.swift, see no such method there.

## Context
I would like to implement a date picker.

## Your Environment
Cocoapods 1.1
CVCalendar (1.4.1)
iPad 2
Simulator

**Comment by kutakmir** [comment]
Solution!

https://github.com/CVCalendar/CVCalendar/issues/56

**Comment by elsesiy** [comment]
@kutakmir As you found the solution by yourself I'm gonna close this issue for now. If you've further questions feel free to open a new isuse!
