### ISSUE TITLE
Option to enable all days in the past until today, rather than from today onwards

### ISSUE THREAD

**Issue by bizz84** [CVCalendar/CVCalendar#434]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
CVCalendar should be configurable so that it's possible to select days in the past rather than in the future. 

May be related to: #233 

## Current Behavior
All days in the past are disabled.

## Possible Solution
Add a configurable valid range to the calendar API:

```swift
struct CalendarValidRange {
   let startDate: Date? // if nil, all days in the past are selectable
   let endDate: Date? // if nil, all days in the future are selectable
}
```

## Context
I'm writing a habits app with a diary page. Users enter data every day and can see their entries from previous days and their improvement over time. I want to use CVCalendar to switch to a day of choice (today or in the past).

## Your Environment
Checked out master and ran demo project on simulator.

**Comment by elsesiy** [comment]
@bizz84 Great catch. Feel free to submit a PR if you find the time 👍

**Comment by raghubb4444** [comment]
Anybody could you please send a sample app(Swift 3.0) using this in your project?
