### ISSUE TITLE
Question: How to make dotMarker the same size as didSelectDayView marker

### ISSUE THREAD

**Issue by RyanHop3** [CVCalendar/CVCalendar#438]
I have set the dotMarker within my project but when I view the calendar the dotMarker is very small compared to the didSelectDayView marker (see attached photo; 31st march is the dotMarker, 30th is the didSelectDayView marker). Is there any way to make the dotMarker look the same as the didSelectDayView marker?
<img width="370" alt="screen shot 2017-03-31 at 20 33 05" src="https://cloud.githubusercontent.com/assets/19892764/24559916/9707b420-1651-11e7-9bac-40d55618f457.png">

**Comment by elsesiy** [comment]
Please use the issue template.

**Comment by RyanHop3** [comment]
The issue template is set up for bugs which this clearly is not. The question and attached photo clearly shows the behavior of the dotmarker compared to the selected dayView which are both in their original state as I have not modified their appearance.

**Comment by salmankhalid876** [comment]
Not completed.
