### ISSUE TITLE
Setup dotmaker

### ISSUE THREAD

**Issue by kaijendo** [CVCalendar/CVCalendar#439]
I very tired to setup it.. it's not showing on calendar.. help me please.. thank you

**Comment by elsesiy** [comment]
Please use the issue template if you need assistance.

**Comment by kaijendo** [comment]
i known, i find all issue but not available. it code in dotmake here: . i'm using swift 3 and xcode 8.3 ios 10.3 
![screen shot 2017-04-05 at 12 41 19 am](https://cloud.githubusercontent.com/assets/16208696/24689296/bd63c5e0-19ef-11e7-895f-21dde38b2386.png)

**Comment by elsesiy** [comment]
@kaijendo I don't understand your problem, please elaborate on it otherwise we cannot provide any help.
