### ISSUE TITLE
CVCalendarView days not matching CVMenuView upon screen rotation

### ISSUE THREAD

**Issue by Fred-White** [CVCalendar/CVCalendar#441]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
When rotating screen CalendarView days should match the MenuView title days (mon, tues etc.)

## Current Behavior
When rotating screen CalendarView days are not matching the MenuView title days (mon, tues etc.). Photo 1 shows CalendarView upon loading view controller, photo 2 shows CalendarView after rotation (days are not matching MenuView) and photo 3 shows calendarView after rotation back to portrait and days are not matching again. Photo 4 shows the layout within the view controller. This is not an issue in the demo project. Code and layout of views appears to be the same as the demo project.

<img width="376" alt="Photo 1" src="https://cloud.githubusercontent.com/assets/27200905/24855199/c583d8ae-1dd8-11e7-97bb-cfe0c61241e2.png">
<img width="667" alt="Photo 2" src="https://cloud.githubusercontent.com/assets/27200905/24855208/cba85d68-1dd8-11e7-8c15-a2f8eb48bddb.png">
<img width="375" alt="Photo 3" src="https://cloud.githubusercontent.com/assets/27200905/24855213/ce0da63a-1dd8-11e7-9f47-6510e08be730.png">
<img width="524" alt="Photo 4" src="https://cloud.githubusercontent.com/assets/27200905/24855217/d1471854-1dd8-11e7-8b41-0bde2242c7d5.png">

## Steps to Reproduce (for bugs)

1. Load view controller and rotate screen.

## Your Environment

* Version used (Cocoapods spec): 1.5.0
* Device used i.e. iPhone 6S: All Devices
* Physical device (y/n): y (iPhone 7, 5s, iPad mini 3)

**Comment by elsesiy** [comment]
@Fred-White This isn't an issue using the demo, it must be a problem on your end. Please provide a sample project if you weren't able to fix this by now.
