### ISSUE TITLE
Today action will enable the earliest-selectable-date which disabled

### ISSUE THREAD

**Issue by aloveric** [CVCalendar/CVCalendar#442]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior

1. Select today button;
2. Calendar show this month, and all days disable which < today.

## Current Behavior

1. Calendar show this month, but all days which < today are enable.
2. Also, most time, today action will not taking effect (nothing happened).

## Steps to Reproduce (for bugs)

1. Set "earliestSelectableDate()" = today;
2. Select today button "calendarView.toggleCurrentDayView()";
3. Calendar show this month, and all days disable which < today.

## Your Environment

* Version used (Cocoapods spec): N/A
* Device used i.e. iPhone 6S: iPhone 6 & iPhone 6sp
* Physical device (y/n): y
* Link to your project (if available): XCode 8.2.1

**Comment by elsesiy** [comment]
@aloveric Yes you were right. From now on the `earliestSelectableDate` is compared to based on the day and not the full UTC timestamp which resolves this issue as well. Please checkout the master to test this again.

**Comment by aloveric** [comment]
@elsesiy Thanks, I will try it.
