### ISSUE TITLE
Month view doesn't appear when pre-selecting a date from a month different from current month

### ISSUE THREAD

**Issue by dhsu210** [CVCalendar/CVCalendar#447]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Problem
I've placed `calendarView.toggleViewWithDate(specifiedDate)` call in `viewDidLoad` and this works fine as expected when loading a date from the month that is the same month as the current month (in this case, May 2017). What I've noticed is that whenever the view controller with the CVCalendar first loads, the first call is to the `didSelectDayView`, during which if i print out `calendarView.coordinator.selectedDayView?.date` in the console, it is preselected to the current date (5/12/17 today). 

i.e.
May 4, 2017 loads perfectly fine with the 4 pre-selected as desired in the displayed month of May
July 6, 2017 shows a blank calendar (menuView shows up fine however)
June 2, 2017 shows a blank calendar (menuView shows up fine however)

If I go a couple layers beneath the surface inside the CVCalendarMonthContentViewController code, the function for `togglePresentedDate(_ date: Foundation.Date)` checks whether or not the months match. For the cases where I have a month such as July or June 2017, the months obviously don't match the preselected `calendarView.coordinator.selectedDayView?.date` (May 2017), which then tells the code that `isMatchedMonths` is false. I'm not sure why, but I think this causes the calendarView to completely blank out. menuView with the day of week labels is still functioning correctly.

I also do have `shouldAutoSelectDayOnMonthChange()` activated to return true or false depending on whether or not the specified date has been preloaded or not. I'm trying to implement functionality where a user can select a date, which dismisses the view controller and passes the selected date back to the parent view controller. Since I was unable to prevent the 1st of each month from being automatically pre-selected every time the user swipes to the right or left (_but if I set the entire `shouldAutoSelectDayOnMonthChange()` to false, then a date will not be pre-selected at all in viewDidLoad)_, I have a bool which checks that the `viewDidLoad` pre-selected specified date occurs, which therefore then sets `shouldAutoSelectDayOnMonthChange()` to false (with an initial true state).

## Possible Solution
If there is a way to set `calendarView.coordinator.selectedDayView?.date` to be that of the specified date that I want to pre-load, I'm thinking the isMatchedMonths in the background code will not cause calendar to disappear. 

Any other suggestions for enabling this feature? 

## Steps to Reproduce (for bugs)

1. Set breakpoints in `viewDidLoad` around `toggleViewWithDate` and around `didSelectDayView`. You'll see didSelectDayView hit twice.
2.

## Your Environment

* Version used (Cocoapods spec): 1.5.0
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
Thanks for reporting this issue @dhsu210. It seems reasonable to allow the user to pre-select a day from another month as stated in your description. If you've the time to look into this in more detail and provide a PR, it'd be highly appreciated.

**Comment by dhsu210** [comment]
@elsesiy Interestingly, I got it to work finally by moving the `toggleViewWithDate` code to viewDidAppear instead of viewDidLoad. The months outside of the current month as well as the loading of the pre-selected date works great now!

**Comment by elsesiy** [comment]
Glad you got it to work so easily, I'm going ahead and close this issue then 👍

**Comment by dhsu210** [comment]
@elsesiy well actually I just noticed that for preselected dates within the current month, the selectionBackground color (circle) doesn't show up. It works fine for months outside of the current month though

**Comment by dhsu210** [comment]
@elsesiy I'm also using the `dayLabelColor` and `dayLabelBackgroundColor` functions from your demo code
