### ISSUE TITLE
Need update with Swift 3.0

### ISSUE THREAD

**Issue by RajkumarThyadi** [CVCalendar/CVCalendar#448]
I included CVCalendar in my project through pods , it showing errors with Swift 3.0 . Its working fine with Swift 2.3. We need update of this framework with Swift3.0

 [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
This is just not true, please see other issues.
