### ISSUE TITLE
Having problem with swift 3..

### ISSUE THREAD

**Issue by casterfile** [CVCalendar/CVCalendar#449]
I am having problem.... i  am using swift 3 and Xcode 8.3.2..
Can you help me?

<img width="1920" alt="screen shot 2017-06-02 at 5 32 16 pm" src="https://cloud.githubusercontent.com/assets/9378129/26720142/a92d6b6a-47b9-11e7-96c0-7c667b14ccf2.png">
![Uploading Screen Shot 2017-06-02 at 5.32.28 PM.png…]()
![Uploading Screen Shot 2017-06-02 at 5.32.43 PM.png…]()

**Comment by sategroup** [comment]
Could you please describe the problem?

**Comment by elsesiy** [comment]
@casterfile Can't reproduce, please provide sample project or steps to reproduce otherwise we can't help you.

**Comment by casterfile** [comment]
Hi... sorry for that... here is the project that i have created... https://github.com/casterfile/Swift-Custom-Date

**Comment by elsesiy** [comment]
@casterfile Please check the demo for how to properly initialize this library.
