### ISSUE TITLE
Not showing Present Date 

### ISSUE THREAD

**Issue by Sreekanth001** [CVCalendar/CVCalendar#451]
## Please Look at this below 

1.   It's showing Sunday date,,,, It's not showing present date

<img width="379" alt="screen shot 2017-06-08 at 10 24 22 pm" src="https://user-images.githubusercontent.com/25745802/26940857-e678615c-4c99-11e7-8bce-c351fb6652ed.png">

2.  If I selected 10-06-2017 and after done button tapped it goes BackViewController...then if I want 
    Change the date 10-06-2017 to some date,,,,that time not showing 10-06-2017 ...

<img width="380" alt="screen shot 2017-06-08 at 10 42 20 pm" src="https://user-images.githubusercontent.com/25745802/26941338-c9a8fa94-4c9b-11e7-92b7-5442df3ce9c6.png">

**Comment by elsesiy** [comment]
Please use the issue template.
