### ISSUE TITLE
Not showing present date

### ISSUE THREAD

**Issue by Sreekanth001** [CVCalendar/CVCalendar#452]
- [ X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Expected Behavior

1.It's showing Sunday date. It's not showing present date

<img width="391" alt="screen shot 2017-06-13 at 12 46 06 pm" src="https://user-images.githubusercontent.com/25745802/27093464-69efb402-5084-11e7-898e-3c4ca2f85d95.png">

2. If I selected 15-06-2017 and after done button tapped it goes BackViewController.Then if I want
  Change the date 15-06-2017 to some date, that time not showing 15-06-2017 date...

<img width="371" alt="screen shot 2017-06-13 at 10 02 51 pm" src="https://user-images.githubusercontent.com/25745802/27093613-06bbb24a-5085-11e7-968e-3f08f0da43f4.png">

My code is 👎  

import UIKit
import CVCalendar

class CalendarViewController: BaseViewController{
    
    struct Color {
        static let selectedText = UIColor.white
        static let text = UIColor.black
        static let textDisabled = UIColor.gray
        static let selectionBackground = UIColor(red: 0.2, green: 0.2, blue: 1.0, alpha: 1.0)
        static let sundayText = UIColor(red: 1.0, green: 0.2, blue: 0.2, alpha: 1.0)
        static let sundayTextDisabled = UIColor(red: 1.0, green: 0.6, blue: 0.6, alpha: 1.0)
        static let sundaySelectionBackground = sundayText
    }
    
    @IBOutlet weak var selectedDateLabel: UILabel!
    @IBOutlet weak var monthLabel: UILabel!
    @IBOutlet weak var calenderView: CVCalendarView!
    @IBOutlet weak var menuView: CVCalendarMenuView!
 
    var homeId:HomeCellTypeId!
    
    var selectedDay:DayView!
    var shouldShowDaysOut = true
    var animationFinished = true
    override func initialCall() {
        self.showclosebutton = true
        var dateString =  SharedModel.shared.selected_values[homeId]
        if dateString == nil || dateString == "" {
            dateString = Date().standardDate()
        }
        calenderView.presentedDate = CVDate(date: Date.fromStandardDate(dateString!)!)
        self.monthLabel.text = calenderView.presentedDate.globalDescription
        self.selectedDateLabel.text = calenderView.presentedDate.commonDescription
        
        calenderView.toggleViewWithDate(Date.fromStandardDate(dateString!)!)
        selectedDay = calenderView.coordinator.selectedDayView
        
        self.navigationItem.leftBarButtonItem = UIBarButtonItem(title: "Select", style: .done, target: self, action: #selector(selectButtonCliked))
        
        if homeId == .from {
            self.title = "Departure date"
        } else if homeId == .to{
            self.title = "Return date"
        }
    }
    
    //@method: select button got clicked
    func selectButtonCliked() {
        if homeId == .departDate {
            SharedModel.shared.selected_values[.departDate] = selectedDay.date.convertedDate()?.standardDate()
        } else if homeId == .returnDate {
            SharedModel.shared.selected_values[.returnDate] = selectedDay.date.convertedDate()?.standardDate()
        }
        //self.dismiss(animated: true, completion: nil)
        self.navigationController?.popViewController(animated: true)
    }
    
    @IBAction func doneButtonClicked(_ sender: Any) {
        self.selectButtonCliked();
    }
    
    @IBAction func cancelButtonClicked(_ sender: Any) {
        //self.dismiss(animated: true, completion: nil)
        self.navigationController?.popViewController(animated: true)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        // Commit frames' updates
        self.menuView.commitMenuViewUpdate()
        self.calenderView.commitCalendarViewUpdate()
    }
}

// MARK: - CVCalendarViewDelegate & CVCalendarMenuViewDelegate

extension CalendarViewController: CVCalendarViewDelegate, CVCalendarMenuViewDelegate {
    
    /// Required method to implement!
    func presentationMode() -> CalendarMode {
        return .monthView
    }
    
    /// Required method to implement!
    func firstWeekday() -> Weekday {
        return .sunday
    }
    
    // MARK: Optional methods
    
    func dayOfWeekTextColor(by weekday: Weekday) -> UIColor {
        return weekday == .sunday ? UIColor(red: 1.0, green: 0.5, blue: 0.5, alpha: 1.0) : UIColor.white
    }
    
    func shouldShowWeekdaysOut() -> Bool {
        return shouldShowDaysOut
    }
    
    func shouldAnimateResizing() -> Bool {
        return true // Default value is true
    }

    func didSelectDayView(_ dayView: CVCalendarDayView, animationDidFinish: Bool) {
        self.selectedDateLabel?.text = dayView.date.commonDescription
        self.selectedDay = dayView
    }
    
    func presentedDateUpdated(_ date: CVDate) {
        if monthLabel.text != date.globalDescription && self.animationFinished {
            let updatedMonthLabel = UILabel()
            updatedMonthLabel.textColor = monthLabel.textColor
            updatedMonthLabel.font = monthLabel.font
            updatedMonthLabel.textAlignment = .center
            updatedMonthLabel.text = date.globalDescription
            updatedMonthLabel.sizeToFit()
            updatedMonthLabel.alpha = 0
            updatedMonthLabel.center = self.monthLabel.center
            
            let offset = CGFloat(48)
            updatedMonthLabel.transform = CGAffineTransform(translationX: 0, y: offset)
            updatedMonthLabel.transform = CGAffineTransform(scaleX: 1, y: 0.1)
            
            UIView.animate(withDuration: 0.35, delay: 0, options: UIViewAnimationOptions.curveEaseIn, animations: {
                self.animationFinished = false
                self.monthLabel.transform = CGAffineTransform(translationX: 0, y: -offset)
                self.monthLabel.transform = CGAffineTransform(scaleX: 1, y: 0.1)
                self.monthLabel.alpha = 0
                
                updatedMonthLabel.alpha = 1
                updatedMonthLabel.transform = CGAffineTransform.identity
                
            }) { _ in
                
                self.animationFinished = true
                self.monthLabel.frame = updatedMonthLabel.frame
                self.monthLabel.text = updatedMonthLabel.text
                self.monthLabel.transform = CGAffineTransform.identity
                self.monthLabel.alpha = 1
                updatedMonthLabel.removeFromSuperview()
            }
            
            self.view.insertSubview(updatedMonthLabel, aboveSubview: self.monthLabel)
        }
    }
    
    func topMarker(shouldDisplayOnDayView dayView: CVCalendarDayView) -> Bool {
        return true
    }
    
    
    func weekdaySymbolType() -> WeekdaySymbolType {
        return .short
    }
    
    func selectionViewPath() -> ((CGRect) -> (UIBezierPath)) {
        return { UIBezierPath(rect: CGRect(x: 0, y: 0, width: $0.width, height: $0.height)) }
    }
    
    func shouldShowCustomSingleSelection() -> Bool {
        return false
    }
    
    func preliminaryView(viewOnDayView dayView: DayView) -> UIView {
        let circleView = CVAuxiliaryView(dayView: dayView, rect: dayView.bounds, shape: CVShape.circle)
        circleView.fillColor = .colorFromCode(0xCCCCCC)
        return circleView
    }
    
    func preliminaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        if (dayView.isCurrentDay) {
            return true
        }
        return false
    }
    
    func dayOfWeekTextColor() -> UIColor {
        return UIColor.white
    }
    
    func dayOfWeekBackGroundColor() -> UIColor {
        return UIColor.orange
    }
}

extension CalendarViewController: CVCalendarViewAppearanceDelegate {
    func dayLabelPresentWeekdayInitallyBold() -> Bool {
        return false
    }
    
    func spaceBetweenDayViews() -> CGFloat {
        return 0
    }
    
    func dayLabelFont(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIFont { return UIFont.systemFont(ofSize: 14) }
    
    func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        switch (weekDay, status, present) {
        case (_, .selected, _), (_, .highlighted, _):
            return Color.selectedText
        case (.sunday, .in, _):
            return Color.sundayText
        case (.sunday, _, _):
            return Color.sundayTextDisabled
        case (_, .in, _):
            return Color.text
        default:
            return Color.textDisabled
        }
    }
    
    func dayLabelBackgroundColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        switch (weekDay, status, present) {
        case (.sunday, .selected, _), (.sunday, .highlighted, _): return Color.sundaySelectionBackground
        case (_, .selected, _), (_, .highlighted, _): return Color.selectionBackground
        default: return nil
        }
    }
}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):-    'CVCalendar', '~> 1.5.0'                         
* Device used i.e. iPhone 6S: iPhone 7

**Comment by Sreekanth001** [comment]
Please help me

**Comment by chanonly123** [comment]
override method of `CVCalendarViewAppearanceDelegate`
`func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        switch (weekDay, status, present) {
        case (_, .selected, _), (_, .highlighted, _): return Color.selectedText
        case (.sunday, .in, _): return Color.sundayText
        case (.sunday, _, _): return Color.sundayTextDisabled
        case (_, .in, _): return Color.simpleText
        default: return Color.textDisabled
        }
    }`
Like in demo app.

**Comment by pontus-ekhem** [comment]
the dayLabelColor function is not being called on opening the viewController. It is only called when I then select a new date. How can I call the function on viewDidLoad?

**Comment by Sreekanth001** [comment]
@chanonly123  did u solve ur problem?

**Comment by chanonly123** [comment]
Yes! its working in my app. Demo app working fine, Try to use that.

**Comment by Sreekanth001** [comment]
@chanonly123, Just downloaded the code and ran Demo app, attached the screenshot. Can you share your screenshot if possible how it looks...
<img width="1440" alt="screen shot 2017-07-15 at 8 23 51 pm" src="https://user-images.githubusercontent.com/25745802/28240253-b133b1bc-699b-11e7-8147-73ccded21a31.png">

**Comment by chanonly123** [comment]
I have created the minimum code required for you. Overriding dayLabelColor.
```import UIKit
import CVCalendar

class ViewController: UIViewController {

    @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.calendarView.calendarAppearanceDelegate = self
        self.calendarView.calendarDelegate = self
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        menuView.commitMenuViewUpdate()
        calendarView.commitCalendarViewUpdate()
    }
    
}

extension ViewController: CVCalendarViewDelegate, CVCalendarMenuViewDelegate {
    
    func presentationMode() -> CalendarMode {
        return CalendarMode.monthView
    }
    
    func firstWeekday() -> CVCalendar.Weekday {
        return CVCalendar.Weekday.sunday
    }
    
}

extension ViewController: CVCalendarViewAppearanceDelegate {
    func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        return UIColor.brown
    }
}
```

you can download testing repo from [here](https://github.com/chanonly123/CVCalendar-Testing)

**Comment by elsesiy** [comment]
Thanks @chanonly123 for helping out. This is considered resolved then!
