### ISSUE TITLE
How do I get the weekly dates to continue in full weekly periods?

### ISSUE THREAD

**Issue by pontus-ekhem** [CVCalendar/CVCalendar#453]
Hi, 

I love the weekly horizontal scroll function but i am trying to get the dates to continue on weekly in full. 

i.e. if I show the out dates i see the same dates grayed out on the next scroll. How can I just remove these grey duplicates from the array so that the dates continue on as normal? 

**EXAMPLE**
currently (view of weekly dates):
|  20 21 22 23 24 25 26  |  27 28 29 30 31 **1 2** | **27 28 29 30 31** 1 2 | 3 4 5 6 7 8 9  |

what I would like (merging sections 2 and 3 - basically deleting the bold values above):
|  20 21 22 23 24 25 26  |  **27 28 29 30 31 1 2** |  3 4 5 6 7 8 9  |

**Comment by elsesiy** [comment]
Please use the issue template.
