### ISSUE TITLE
Change CVCalendarViewPresentationMode from monthView to weekView automatically when user sellects a particular date. 

### ISSUE THREAD

**Issue by KhanhThoNguyen** [CVCalendar/CVCalendar#456]
Change CVCalendarViewPresentationMode from monthView to weekView automatically when a user selects a particular date. 
```
if calendarView.calendarMode == .monthView {
            calendarView.changeMode(.weekView)
}
```
I put this code into func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool). But I met a lot of bugs.
Please Help me.

**Comment by elsesiy** [comment]
Please use the issue template.
