### ISSUE TITLE
Change colour of text within dates with circles

### ISSUE THREAD

**Issue by fweathers** [CVCalendar/CVCalendar#458]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior

I was wondering if there was a way to change the text colour of the date that is within the dotMarker. For instance, if my dotMarker has a fill in colour, and the remainder of the text for the dates are black, I would want to change my text to white if it is a preselected date with a circle around it.

## Current Behavior

Currently, you can change the text colour for `in`, out, .highlighted, .selected dates but not for the dates within the circle.

func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        switch (weekDay, status, present) {
        case (_, .selected, _), (_, .highlighted, _): return Color.selectedText
        case (.sunday, .in, _): return Color.sundayText
        case (.sunday, _, _): return Color.sundayTextDisabled
        case (_, .in, _): return Color.text
        default: return Color.textDisabled
        }

## Possible Solution

i want to fill in my preselected dates (i.e. have a due date) so the circle is filled in like the selected circle but with a different colour and be able to change the text so that it is more legible

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n): Y iPhone 7
* Link to your project (if available):

**Comment by elsesiy** [comment]
This is not an issue specific to this library.
