### ISSUE TITLE
Calendar current date not showing properly like it did on the swift 2 version

### ISSUE THREAD

**Issue by klevis94** [CVCalendar/CVCalendar#459]
I changed CVCalendar from the swift two version to the swift 3 version and i'm having an issue with the way the calendar works and displays the current date and other animations regarding selecting other dates. 
Attached is the issue and how it currently behaves. Thank You
![screen shot 2017-06-27 at 4 50 30 pm](https://user-images.githubusercontent.com/17086995/27594509-3f5b75f6-5b5a-11e7-9b74-8e84fb316685.png)
![screen shot 2017-06-27 at 4 50 53 pm](https://user-images.githubusercontent.com/17086995/27594511-3f5edc0a-5b5a-11e7-9d37-32d18523468f.png)
![screen shot 2017-06-27 at 4 51 05 pm](https://user-images.githubusercontent.com/17086995/27594510-3f5e28a0-5b5a-11e7-8583-91365d722fcf.png)

**Comment by hengchengfei** [comment]
have same error

**Comment by Sreekanth001** [comment]
I have also same error

**Comment by chanonly123** [comment]
override method of `CVCalendarViewAppearanceDelegate`
`func dayLabelColor(by weekDay: Weekday, status: CVStatus, present: CVPresent) -> UIColor? {
        switch (weekDay, status, present) {
        case (_, .selected, _), (_, .highlighted, _): return Color.selectedText
        case (.sunday, .in, _): return Color.sundayText
        case (.sunday, _, _): return Color.sundayTextDisabled
        case (_, .in, _): return Color.simpleText
        default: return Color.textDisabled
        }
    }`
Like in demo app.

**Comment by elsesiy** [comment]
As @chanonly123 correctly stated, please see the demo app on how to integrate this library.
