### ISSUE TITLE
current date is not click-able on first load

### ISSUE THREAD

**Issue by chanonly123** [CVCalendar/CVCalendar#461]
Present current date is not click-able on first load

**Comment by daltyboy11** [comment]
I too have noticed this problem

**Comment by Sreekanth001** [comment]
@chanonly123   did u solve ur problem?

**Comment by chanonly123** [comment]
Not yet!

**Comment by Sreekanth001** [comment]
But just now, u were put a message in my issue #452  ....Your are meassage is " Yes! its working in my app. Demo app working fine, Try to use that. "....Then finally demo app working fine? .. I am Waiting for ur response !

**Comment by chanonly123** [comment]
Sorry I accidentally closed this issue.
I have a minimal testing repo [here](https://github.com/chanonly123/CVCalendar-Testing)
On first load current day is not clickable.

**Comment by elsesiy** [comment]
@chanonly123 I checked your sample project and found indeed an issue in how the initial loading is done. I do have a fix but I can't estimate how it affects delegate calling and other side effects so I need to do some more testing before pushing it.
