### ISSUE TITLE
Calendar showing wrong prev/next month

### ISSUE THREAD

**Issue by antons81** [CVCalendar/CVCalendar#465]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Expected Behavior
I initializing calendar and it's showing present month, then click next button and it's again showing present month, then click next again and it's showing next month, then I click prev button and showing next month, please see following flow:
init -> July -> July -> August <- September

## Steps to Reproduce (for bugs)
http://www.giphy.com/gifs/3oeHLlFg1Ufa5bJokw - here is giphy about the bug

## Context
It's affecting to project and I tried to recognize the issue in source code

## Your Environment

* Version used (Cocoapods spec): 1.3.0.beta.2
* Device used i.e. iPhone 6S: iPhone 7
* Physical device (y/n): y

**Comment by elsesiy** [comment]
Please have a look at the demo to make sure you have all the init logic properly set up. If the issue still exists then, please provide a sample project.

**Comment by antons81** [comment]
This issue have been resolved. Found delegate method updating months
