### ISSUE TITLE
Programmatically create and show the Calendar

### ISSUE THREAD

**Issue by Drakot** [CVCalendar/CVCalendar#468]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

I have followed the Manual instructions to implement the calendar, but there it does not show the calendar. ContentViewController is nil for some reason, is there a more detailed tutorial? because I cannot find where is the SHOW calendar example.

Thank you

**Comment by elsesiy** [comment]
@Drakot I don't have any more detailed information on how to set it up, sorry.

**Comment by NSMyself** [comment]
I'm going to state the obvious because it might help someone and the instructions don't mention it: we still need to add those views to the view itself, of course.

**Comment by zhukovka** [comment]
@Drakot I think the manual is missing one step: `self.view.addSubview(self.calendarView!)`

**Comment by elsesiy** [comment]
@zhukovka Feel free to update the documentation accordingly, thanks!
