### ISSUE TITLE
Gesture behind calendar

### ISSUE THREAD

**Issue by yayoro** [CVCalendar/CVCalendar#469]
Hello,

I am using CVCalendar in my ios app.

I have a table view behind calendar. I need when i am doing scroll down in table view, calendar changes from Week style to Month style with a simple animation, and when i am doing scroll up in my table view, calendar changes from Month style to Week style.

Is possible make this? i dont know who do it :(

Thanks you so much.

**Comment by elsesiy** [comment]
Sorry, but this is not an issue with this library. Please ask such questions on [SO](https://stackoverflow.com/).
