### ISSUE TITLE
Initial circle is missing 

### ISSUE THREAD

**Issue by Huddie** [CVCalendar/CVCalendar#470]
The circle around the numbers is missing. Replication is just the normal implementation.

**Comment by elsesiy** [comment]
I just checked the Demo, everything works as intended. There're no circles if you use range selection and for single selection the circle for today is there.

**Comment by Huddie** [comment]
It works for me on 1.4.1 not 1.5+

**Comment by elsesiy** [comment]
It's not a "guaranteed" bug, see #444 #451 #452 and the demo for reference.
