### ISSUE TITLE
CircleView does not appear on start.

### ISSUE THREAD

**Issue by arekotto** [CVCalendar/CVCalendar#471]
This bug is a follow up to issue 440. I'm using the newest version 1.5.1 on the Swift4 branch. I have included screenshots and a sample project which demonstrates the bug.

## Expected Behavior
When the view controller appears, current date should be selected with circleView.

## Current Behavior
When the view controller appears, current date label is white with no circleView around it. Selecting another date fixes the issue. 

## Steps to Reproduce (for bugs)
1. Setup the view as stated in the instructions. 

![img_0253](https://user-images.githubusercontent.com/23309349/30057395-d3deb072-9236-11e7-835e-246c132a56a4.PNG)
![img_0254](https://user-images.githubusercontent.com/23309349/30057396-d4442556-9236-11e7-946c-d601888f44a0.PNG)
![img_0255](https://user-images.githubusercontent.com/23309349/30057394-d3d5c372-9236-11e7-9b04-44420021d98c.PNG)
[CVTest.zip](https://github.com/CVCalendar/CVCalendar/files/1277098/CVTest.zip)

**Comment by classified** [comment]
is there any other workaround for this?

**Comment by arekotto** [comment]
What I've currently done is call toggleViewWithDate() twice, with different dates as toggling the dates makes it go away. It does look really bad, but I wasn't able to come up with anything better. If you're on Swift 3 and xcode 8 revert to version 1.4.0 as the bug was not present there for me.

**Comment by classified** [comment]
ok thanks

**Comment by ReckeDJ** [comment]
Same bug here, reverting to 1.4.1 for now.

**Comment by elsesiy** [comment]
I'm not able to reproduce this with 1.5.1. and the Demo. The only changes I made are:
1. `shouldSelectRange()` to return `false`
2. Add `calendarView.toggleCurrentDayView()` to `viewDidLoad`

The calendar shows all dates and the current day is selected respectively. I'll try your project @arekotto  once I update XCode sometime next week.

**Comment by arekotto** [comment]
Thanks for the answer  @elsesiy. I have also created a swift 3 project that might help you reproduce it. 
[CVTestSwift3.zip](https://github.com/CVCalendar/CVCalendar/files/1289911/CVTestSwift3.zip)

**Comment by elsesiy** [comment]
I found the issue and just pushed a fix. Can you please try with the latest master again @arekotto ?

**Comment by arekotto** [comment]
@elsesiy works like a charm! Thanks :)

**Comment by elsesiy** [comment]
Great, I'll release a fix soon then :)

**Comment by elsesiy** [comment]
@arekotto Just released `1.5.2` and updated the `swift4` branch accordingly.
