### ISSUE TITLE
`disableScrollingBeforeDate()` doesn't work, and `disableScrollingBeyondDate()` doesn't work correctly.

### ISSUE THREAD

**Issue by YorrickBao** [CVCalendar/CVCalendar#474]
- [Y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y] I have verified that I am using the latest version of CVCalendar.
- [Y] I have given my issue a non-generic title.

## Expected Behavior
1: Scrolling to previous month behavior should be disabled before the date specified from delegate method `disableScrollingBeforeDate()`

2: Scrolling to next month behavior should be disabled beyond the date specified from delegate method `disableScrollingBeyondDate()`

## Current Behavior
1: Scrolling to previous month behavior is disabled upon the date specified from delegate method `disableScrollingBeyondDate()`

2: Scrolling to next month behavior could not be disabled whether implemented `disableScrollingBeyondDate()` nor implemented `disableScrollingBeyondDate()`

**Comment by jdrevet** [comment]
This issue has been resolved by commit 2829893.
@elsesiy Do you plan to release a 1.6.1 with the last fixes ?

**Comment by elsesiy** [comment]
@jdrevet I'm currently very busy, maybe on the weekend..

**Comment by georgiosantoniadis** [comment]
Hi. As I understand the commit mentioned above, it fixes the `latestSelectableDate` and `earliestSelectableDate.` Does it also fix the disableScrolling...() methods?

The only code snipped I found where the `disableScrollingBeyondDate` variable is used, is in the function `checkScrollToPreviousDisabled()`. 
My suggestion is, to `disableScrollingBeforeDate`, that there must also exist a `checkScrollToNextDisabled()` or similar.

Is that a correct assumption?
