### ISSUE TITLE
Calendar don't collapse correctly. Its happens once in ten or more

### ISSUE THREAD

**Issue by yayoro** [CVCalendar/CVCalendar#477]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ X] I have given my issue a non-generic title.

## Expected Behavior
I have a problem. 
Once you change from month to week, the view does not collapse. I have the constraint well set, but as I say happens once in 10 I do this

## Steps to Reproduce (for bugs)
1. Enter in app
2. Change from month to week. Calendar collapse correctly
![img_0415](https://user-images.githubusercontent.com/26386809/30782367-55c50e02-a131-11e7-9ae7-d82a1ccfc3a0.jpg)

3. Change from week to month. Calendar expand correctly.
4. Repeat point two, and happens once in ten or more that I do this
![img_0404 2](https://user-images.githubusercontent.com/26386809/30782394-fe339270-a131-11e7-8361-c79c5a080481.jpg)

## Your Environment
* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S: iPhone 7 with IOS 11
* Physical device (y/n): iPhone 7

**Comment by Huddie** [comment]
+1

**Comment by elsesiy** [comment]
@yayoro Can you provide a sample to reproduce this please?

**Comment by yayoro** [comment]
In this moment, I can´t provide you a sample. In next days I will try provide you.
