### ISSUE TITLE
Xcode 9 + Swift 4 errors - Declarations from extensions cannot be overridden yet 

### ISSUE THREAD

**Issue by woutergoossens** [CVCalendar/CVCalendar#479]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of CVCalendar.
- [X] I have given my issue a non-generic title.

## Expected Behavior
Updated to Xcode 9 and Swift 4 and don't receive an error.

## Current Behavior
Updated to Xcode 9 and Swift 4 and getting multiple errors.
- Declarations from extensions cannot be overridden yet 
- Ambiguous use of 'presentPreviousView'

## Steps to Reproduce (for bugs)
Screenshots:
<img width="456" alt="screen shot 2017-09-29 at 17 01 11" src="https://user-images.githubusercontent.com/355048/31022006-d2ea64fe-a537-11e7-9d98-cd33592ae250.png">
<img width="849" alt="screen shot 2017-09-29 at 17 01 28" src="https://user-images.githubusercontent.com/355048/31022019-db33a71a-a537-11e7-8d43-d0461d3372b8.png">

## Your Environment

* Version used (Cocoapods spec): 1.5.2
* Device used i.e. iPhone 6S: iPhone 8
* Physical device (y/n): n
* Link to your project (if available):

**Comment by elsesiy** [comment]
Please see #478. Obviously you missed this one... I just released 1.6.0 which defaults to swift4 syntax.

**Comment by woutergoossens** [comment]
Great! Thanks. Sorry missed that one indeed
