### ISSUE TITLE
Not able to select a specific day when I shift in a new week, but it selects the current day automatically

### ISSUE THREAD

**Issue by cannaz** [CVCalendar/CVCalendar#486]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
I should be able to decide which day to select when I swipe on a new week or month

## Current Behavior
When I shift in the current week, in week mode, it selects the current day automatically.

## Possible Solution
I just commented this block and I have at least always the first day of the week
```
if let selected = coordinator?.selectedDayView ,
                    !matchedWeeks(selected.date, presentedDate) &&
                        calendarView.shouldAutoSelectDayOnWeekChange {
                    let current = CVDate(date: Foundation.Date(), calendar: calendar)

//                            if matchedWeeks(current, presentedDate) {
//                                selectDayViewWithDay(current.day, inWeekView: presentedWeekView)
//                            } else {
                                selectDayViewWithDay(presentedDate.day,
                                                     inWeekView: presentedWeekView)
//                            }
                }
```

## Your Environment

* Version used (Cocoapods spec): 
* Device used i.e. iPhone 6S: iPhone 6s
* Physical device (y/n): y
* Link to your project (if available):

**Comment by cherick04** [comment]
which version of CVCalendar are you using? i'm assuming 1.6.0?

**Comment by elsesiy** [comment]
@cannaz Is this still an issue?
