### ISSUE TITLE
Dot marker moves down to the date right beneath it when a date with dot marker is selected

### ISSUE THREAD

**Issue by dramanpk** [CVCalendar/CVCalendar#490]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
The event dot marker should stay where it is even after selecting the date.

## Current Behavior
The dot marker moves to the date right below the selected date

## Steps to Reproduce (for bugs)
1. Implement the dot marker delegate methods to mark the required dates with dots
2. Select the date that has an event (marked by dot)
3. Notice the dot marker moves down to the date right below the selected date

## Context
When the dot moves down to bottom date from the selected date, it confuses the user. The user would assume there is an event on the other date as well.

## Your Environment
I am using an iPhone 6S
CVCalendar Version 1.6

**Comment by dramanpk** [comment]
@elsesiy Could you please take a look into this issue?

**Comment by dramanpk** [comment]
@elsesiy Do you think a screenshot would suffice? In the attached screenshot, inside the red annotated area you could see the dot market is marking the date below the selected date. Please use this for your bug investigation, while I get ready with a sample project reproducing the issue.

![img_0499](https://user-images.githubusercontent.com/29310063/34082159-5d28c842-e316-11e7-9963-9e1945203c19.jpg)

**Comment by dramanpk** [comment]
I am sorry this i

**Comment by dramanpk** [comment]
I am sorry this not a bug. It is just that I have not implemented one of the delegate methods. Sorry about that. I am closing this now. Thanks @elsesiy

**Comment by oniikal3** [comment]
@dramanpk How did you fixed it?. I'm facing with this issue too.

**Comment by dcarra01** [comment]
@dramanpk @oniikal3 Could you give me the solution to this issue? I have the same problem. Thank you

**Comment by retsohuang** [comment]
You can implement `dotMarker(shouldMoveOnHighlightingOnDayView:)` delegate method to prevent dot marker moves down while selection.
