### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Jaypixster** [CVCalendar/CVCalendar#496]
The Error is in CalenderAppereanceDelegate On Run time

**Comment by iKisliy** [comment]
You should use issue template (path: CVCalendar/.github/ISSUE_TEMPLATE.md)

**Comment by elsesiy** [comment]
@iKisliy thanks you!! 
@Jaypixster Can't reproduce, check the Demo.
