### ISSUE TITLE
Wrong Date Print

### ISSUE THREAD

**Issue by Jaypixster** [CVCalendar/CVCalendar#497]
func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) {
        
        print(dayView.date.convertedDate())
        
    }

When i Print Date Than it print Selected Date-1  it means if i Select 27 than it print 26 :(

**Comment by tayo119** [comment]
I have the same issue: didSelectDayView function always reference to previous day not to selected day

**Comment by elsesiy** [comment]
@Jaypixster Firstly, please use the issue template. It provides valuable info for debugging the issue, now I have to ask you a bunch of questions instead. Second, I can't reproduce this at all, so please provide a sample project for me to look at. Thanks!

**Comment by RameshwarAIS** [comment]
I have the same issue: it will print 1 day previous date

**Comment by elsesiy** [comment]
@RameshwarAIS Could you provide a sample project, please?

**Comment by RameshwarAIS** [comment]
@elsesiy can you please provide mail id for the same

**Comment by elsesiy** [comment]
@RameshwarAIS Yes you can use github@elsesiy.com, thank you!

**Comment by RameshwarAIS** [comment]
[CVDemo_DateIssue.zip](https://github.com/CVCalendar/CVCalendar/files/1922574/CVDemo_DateIssue.zip)

- Here I attach demo for the same. Please check log.

**Comment by RameshwarAIS** [comment]
- issue in    **dayView.date.convertedDate()**
