### ISSUE TITLE
How to localize MenuView

### ISSUE THREAD

**Issue by Wiingaard** [CVCalendar/CVCalendar#498]
I'm trying to Localize the Menuview, so the day labels will display the danish name instead:

Currently they show:  
M T W T F S S
On danish that should be:
M T O T F L S

I've implementer `calendar()` from `CVCalendarViewDelegate`, and it gets called!
```
func calendar() -> Calendar? {
    let calendar = self.myCalendar
    print(calendar.locale)
    return calendar
}
```
When printing the `Locale` of the calendar, I see `da_DK (fixed)` as expected, but the menuview seems to remain in English Locale.

**How do I change the `Locale` of the `MenuView`?**

**Comment by User106** [comment]
Just go to Project->"Localizations" add Danish.
All is well. @Wiingaard

**Comment by elsesiy** [comment]
This shouldn't be an issue as @User106 described. Please use the issue template in the future.

**Comment by muhasturk** [comment]
Assign same localized calendar object to menuView before assigning menuView delegate. Thus menu view is gonna be localized.


```swift
    currentCalendar = Calendar(identifier: .gregorian)
    currentCalendar?.locale = Locale(identifier: "tr_TR")

    menuView.calendar = currentCalendar

    menuView.menuViewDelegate = self
```

**Comment by iletai** [comment]
> @Wiingaard Assign same localized calendar object to menuView before assigning menuView delegate. Thus menu view is gonna be localized.
> 
> ```swift
>     currentCalendar = Calendar(identifier: .gregorian)
>     currentCalendar?.locale = Locale(identifier: "tr_TR")
> 
>     menuView.calendar = currentCalendar
> 
>     menuView.menuViewDelegate = self
> ```

I personally think it's will be helpful for someone to find a solution for localizing the menu view.
