### ISSUE TITLE
CalendarMode init with WeekView mode error

### ISSUE THREAD

**Issue by yayoro** [CVCalendar/CVCalendar#499]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of CVCalendar.
- [X] I have given my issue a non-generic title.

If I start application with CalendarMode as WeekView, the view don't collapse correctly. Somebody know how this problem resolved?

![captura de pantalla 2017-12-21 a las 20 08 54](https://user-images.githubusercontent.com/26386809/34271153-54704478-e68b-11e7-962c-f76589863e52.png)

**Comment by elsesiy** [comment]
Did you solve this @yayoro ?

**Comment by yayoro** [comment]
Hi @elsesiy I haven´t solved this issue. And you? Do you have any idea why it happens?

**Comment by elsesiy** [comment]
To me this sounds more like a layout constraint issue which you can usually adapt dynamically. What have you tried so far?

**Comment by yayoro** [comment]
I have not been able to prove many things, simply, I have decided not to incorporate this functionality to my application. 

In next days if I can, I provide you an example.
