### ISSUE TITLE
Crashes on iOS 7

### ISSUE THREAD

**Issue by gnrsenpai** [CVCalendar/CVCalendar#50]
Hello and thanks for the calendar component, it's the best i've found for iOS devices.

This component is working properly when i run it on iOS 8 simulator, however, when i try to execute it on my iPod touch with iOS 7 it crashes on the line where it multiplies the value of countOfWeeks \* 7. I did notice that on the method monthDateRange (within CVCalendarManager.swift), the value for the range of the month equals to this on iOS 7: range = Optional((2147483647,2147483647)), the strange thing is that on iOS 8 the value is often between 18 and 6. The crash actually happens because the int variable cannot store a number that large.

Before this problem i had another where it crashed setting the value for the calendar variable, again only on iOS 7 and not iOS 8, so i had to change from:
self.calendar = NSCalendar(identifier: NSCalendarIdentifierGregorian)

to this declaration:
self.calendar = NSCalendar(calendarIdentifier: NSGregorianCalendar)

**Comment by Mozharovsky** [comment]
Hello @gnrsenpai, 

Thank you for your investigation on this issue. 

There were some transparent changes that brought issues in bridging between iOS 7 and iOS 8. As a result some code doesn't work properly on iOS 7 since it was written using the up-to-date SDK. Anyway it's a good idea to check the system version and initialize the problematic instances properly. 

It'll be fixed in the 1.1.0 release. Keep watching! 

Regards, 
Eugene

**Comment by Mozharovsky** [comment]
I'm not sure CVCalendar is going to support iOS 7. If you need older iOS version support I'd recommend to look into [JTCalendar](https://github.com/jonathantribouharet/JTCalendar).

**Comment by gnrsenpai** [comment]
i've actually modified a few lines of the library code to make it work on iOS 7, it isn't hard, the NSCalendar variable, for example, has to be initialized with other parameters on iOS 7

**Comment by wishingsky** [comment]
Hello @gnrsenpai
I met the same problem with you，I want to know how you solve the problem of adaptation on iOS7？can you help me?

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by wishingsky** [comment]
I have solved this problem, to Compatible with iOS 7

        let weekOfMonthUnit: NSCalendarUnit
        if #available(iOS 8, *) {
            weekOfMonthUnit = NSCalendarUnit.WeekOfMonth
        } else {
            weekOfMonthUnit = NSCalendarUnit.NSWeekCalendarUnit
        }
        
        let range = calendar.rangeOfUnit(weekOfMonthUnit, inUnit: MonthUnit, forDate: date)
        let countOfWeeks = range.length

**Comment by Mozharovsky** [comment]
Please do not spam the thread! We'll add iOS 7 support in the upcoming release.

**Comment by elsesiy** [comment]
@wishingsky I just deleted the same 25 comments from you. Could you please be more careful if you post something?

**Comment by Mozharovsky** [comment]
Thank you @elsesiy !

**Comment by wishingsky** [comment]
@elsesiy   I ‘ m sorry，it’s so slow for the network response,  sorry, my fault

**Comment by EdsonGuido** [comment]
If you need to make it work in IOS 7 but don't like  to use  the   #available(iOS 8, *) tag change these two lines in the CVCalendarManager.monthDateRange:
delete `let range = calendar.rangeOfUnit(weekUnit, inUnit: monthUnit, forDate: date)`
delete `let countOfWeeks = range.length`  and 
add `let countOfWeeks = calendar.components(weekUnit, fromDate: monthEndDate).weekOfMonth`

This give the return the  NSCalendarUnit.WeekOfMonth from the monthEndDate that is the is count of weeks in that month.
