### ISSUE TITLE
Calendar does not relayout dates after change from weekView to monthView

### ISSUE THREAD

**Issue by Joe-Bloomfield23** [CVCalendar/CVCalendar#500]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
calendarView dates are expected to relayout upon change from either weekView or screen rotation to fit the size of the view.

## Current Behavior

calendarView dates do not fit the size of the view correctly and the lower portions of the dates are not displayed or display beyond the view when either changing from weekView to monthView or changing from landscape to portrait mode.

I have tried calling calendarView.contentController.refreshPresentedMonth() within viewDidLayoutSubviews() after rotation or calendar mode change but this has no effect no the calendar.

## Steps to Reproduce (for bugs)

1. Begin with calendar in .monthView in portrait mode
2. Either change device to landscape or .weekView
3. Change back to portrait .monthView
4. Calendar no longer has the correct layout with dates missing from the view or extending beyond the view.

<img width="277" alt="screen shot 2018-01-13 at 16 56 35" src="https://user-images.githubusercontent.com/35398780/34906238-c80a5f32-f882-11e7-934c-d01ad6051c41.png">

## Your Environment

* Version used (Cocoapods spec): 1.6.0
* Device used i.e. iPhone 6S: tested on iPhone 6, 7 and X
* Physical device (y/n): Y

**Comment by elsesiy** [comment]
@Joe-Bloomfield23 Thanks for the detailed bug report. I won't find the time to fix this soon, so if it'd be great if you can contribute a fix. Thanks!
