### ISSUE TITLE
remove the seperator lines between rows for month calendar

### ISSUE THREAD

**Issue by chitvan832** [CVCalendar/CVCalendar#501]
## Expected Behavior
CLear background, just digits appearing in calendar

## Current Behavior
Separator lines are present
![screen shot 2018-01-20 at 12 55 47 am](https://user-images.githubusercontent.com/25215903/35167780-b471b700-fd7c-11e7-8887-14b51a3ae70a.png)

**Comment by ccortessanchez** [comment]
Have you tried this method? 
`func topMarker(shouldDisplayOnDayView dayView: CVCalendarDayView) -> Bool {
        return false
    }`

**Comment by elsesiy** [comment]
@ccortessanchez that's correct, thanks for your support.
