### ISSUE TITLE
How to preselect a date interval programmatically?

### ISSUE THREAD

**Issue by Ewg777** [CVCalendar/CVCalendar#510]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

How to preselect a date interval programmatically?
@elsesiy

**Comment by Ewg777** [comment]
@elsesiy, any idea?

**Comment by Ewg777** [comment]
@elsesiy, any idea?

**Comment by elsesiy** [comment]
@Ewg777 You're not giving me any context and provide only half of the issue template.

**Comment by Ewg777** [comment]
@elsesiy let's say we got a page with some filters. Something like this https://ps.w.org/date-range-filter/assets/screenshot-1.png?rev=1454790
When we tap on the textfield the calendar appears with a PRESELECTED DATE INTERVAL. 
@elsesiy Is it more clear now?
Thanks

**Comment by elsesiy** [comment]
I understand what you're requesting but you don't provide any info on what you've tried so far leave alone which versions you're using (that's what the issue template is for).

**Comment by Ewg777** [comment]
@elsesiy the latest vestion doesn't support this, right? Which version are you expecting to put here?

**Comment by Ewg777** [comment]
Any chance?

**Comment by Ewg777** [comment]
Any chance?

**Comment by Ewg777** [comment]
Any chance?
