### ISSUE TITLE
How to customize each single dayview in CVCalendar for swift?

### ISSUE THREAD

**Issue by Steven9593** [CVCalendar/CVCalendar#512]
I am using CVCalendar in order to setup reminders about which days I am occupied. I do so by darkening the background color of the selected dayview:

func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) {    
    if mySwitch.isOn == true {            
        if dayView.backgroundColor == UIColor.brown {
            //This hex string is the default background color
            dayView.backgroundColor = UIColor(hexString: "ff9200")

            if let dateForDeletion = selectedRoom {
                do {
                    try self.realm.write {
                        self.realm.delete(dateForDeletion.details.filter("dateSelected CONTAINS[cd] %@", "\(calendarView.presentedDate.day)-\(calendarView.presentedDate.month)-\(calendarView.presentedDate.year)"))
                    }
                } catch {
                    print("Error deleting room,\(error)")
                }
            }
        } else {
            dayView.backgroundColor = UIColor.brown

            if let currentRoomDetails = self.selectedRoom {
                do {
                    try self.realm.write {
                        let newDateDetail = Detail()

                        newDateDetail.dateSelected = "\(calendarView.presentedDate.day)-\(calendarView.presentedDate.month)-\(calendarView.presentedDate.year)"
                        currentRoomDetails.details.append(newDateDetail)
                    }
                } catch {
                    print("Error saving new details, \(error)")
                }
            }
        }
    }
}

Note that I am using Realm in order to save this information.

The problem arises when I leave the CVcalendar and reload the app. I saved the dates of the selected dayviews on realm, but I am incapable of programmatically reloading specific dayviews which are the ones that corresponds with the saved dates and will have a darkened background color.

for example, I tried this method, which didn't work:

func supplementaryView(viewOnDayView dayView: DayView) -> UIView {    
    if let dateSelected = selectedRoom?.details.value(forKey: "dateSelected") as? String {
        if dateSelected == "\(dayView.date.day)-\(dayView.date.month)-\(dayView.date.year)" {
            dayView.backgroundColor = UIColor.brown
        } else {
             dayView.backgroundColor = UIColor(hexString: "ff9200")!
        }
        dayView.backgroundColor = UIColor(hexString: "ff9200")!
    }
    return dayView
}

func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
    return true
}

**Comment by elsesiy** [comment]
Please use the issue template, otherwise I can't help you.

**Comment by Steven9593** [comment]
what do you mean?
