### ISSUE TITLE
Is there a way to disable "disableDays" on selection?

### ISSUE THREAD

**Issue by Ewg777** [CVCalendar/CVCalendar#515]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

@elsesiy Is there a way to disable "disableDays" on selection? Now selecting a first day disables all previous days.

**Comment by Ewg777** [comment]
@elsesiy any idea?

**Comment by elsesiy** [comment]
@Ewg777 There's no such functionality, no. Feel free to add it yourself!
