### ISSUE TITLE
Selected date not being retained when we move for 2 or more months in either direction and comeback to selected date. 

### ISSUE THREAD

**Issue by vamsivannam** [CVCalendar/CVCalendar#516]
I have given last selectable date and first/oldest selectable date, and disabled few days in between...
For example I selected Apr 25th 2018, I swipe to the month May and come back, apr 25th is retained. But If i go to June or more and go back to Apr , Apr 25th is not preselected and in side CVCalender related classes, calendarView is becoming **nil**,

My requirement is to show dates in 3-4 months, disable few dates in between, toggle between them.
Retain selected date and keep it highlighted even if user swipes to other months and come back to selected month, unless user selects another date.

**Comment by elsesiy** [comment]
Hi @vamsivannam, please use the issue template and provide a proper example project for us to investigate. Otherwise we won't be able to provide any assistance, thank you.

**Comment by vassily-fr** [comment]
same issue for me also when tooggleing from week to month view.
juste launch the sample code, select a day and switch from month view to week view : the selected day is lost

**Comment by elsesiy** [comment]
@vassily-fr @vamsivannam Please re-test with the latest release `1.6.2`, thanks!
