### ISSUE TITLE
Calendar is not showing on iOS 10.x

### ISSUE THREAD

**Issue by cliftonmyers** [CVCalendar/CVCalendar#517]
## Expected Behavior
The Calendar is not showing on iOS 10.3.3

## Current Behavior
The Calendar menu is showing
The Calendar is not showing

## Context
I need to show a calendar date picker, and support OS till 9.0

## Your Environment
* Version used (Cocoapods spec):     pod 'CVCalendar', '~> 1.6.0'
* Device used i.e. iPhone 5S
* Physical device (y/n): y

**Comment by cliftonmyers** [comment]
yes sure, please find my code attached

[Archive.zip](https://github.com/CVCalendar/CVCalendar/files/2026293/Archive.zip)

**Comment by cliftonmyers** [comment]
different devices behavior:
![iPhone 5s - iOS 10.3.3](https://user-images.githubusercontent.com/6988256/40358796-2586f318-5dc9-11e8-91a7-c822451c5985.PNG)

![iPhone 5s - iOS 11.2](https://user-images.githubusercontent.com/6988256/40359082-1f02f202-5dca-11e8-8847-5bc482fb45c6.png)

**Comment by cliftonmyers** [comment]
@ccortessanchez any news?

**Comment by ccortessanchez** [comment]
Sorry @cliftonmyers , I haven't found time to take a look at your code. Did you solve it?

**Comment by cliftonmyers** [comment]
@ccortessanchez no this wasn't fixed and i still need a solution
