### ISSUE TITLE
Scrolling in weekly view going beyond the limited date (checkScrollToPreviousDisabled()  & checkScrollToBeyondDisabled()) need to be implemented in week view.

### ISSUE THREAD

**Issue by karuna2302** [CVCalendar/CVCalendar#522]
- [*] I have verified there are no duplicate active or recent bugs, questions, or requests
- [*] I have verified that I am using the latest version of CVCalendar.
- [*] I have given my issue a non-generic title.

## Expected Behavior
 Weekly view mode user scroll should be restricted with given date range (disableScrollingBeforeDate & disableScrollingBeyondDate)

## Current Behavior
User can able to scroll beyond the given date range(before and after dates) 

## Possible Solution
I looked into the code weekly view switch,
public func initialLoad(_ date: Foundation.Date) -  checkScrollToPreviousDisabled() & checkScrollToBeyondDisabled() not been implemented. 

## Steps to Reproduce (for bugs)
1. Give the Date range in demo app source code in following delegate methods,
- func disableScrollingBeforeDate() -> Date
- func disableScrollingBeyondDate() -> Date 
- func earliestSelectableDate() -> Date
- func latestSelectableDate() -> Date
2. Launch the demo application and switch it to weekly view.
3. Scroll the weekly view left or right side beyond the given date range.
4. Application is restrict the user scroll with given date range.

## Context
 Application should allow the user to scroll and see the date within given date range. 

## Your Environment
* Version used (Cocoapods spec): 1.5.0 (Using CVCalendar (1.6.1))
* Device used i.e. iPhone 6S:  Any device 
* Physical device (y/n):Yes
* Link to your project (if available):

**Comment by barkiiqbal** [comment]
I was also using these methods but it seems these methods are for range selection not for scrolling of month or day view

**Comment by karuna2302** [comment]
@barkiiqbal , Monthly view working fine. I cannot able to scroll or select beyond my date range. (i.e., User should allowed to scroll only 2 month from current month. For example if the user in weekly view, he can able to scroll to any month (Dec also) in current master build.)

**Comment by nikita-11-04** [comment]
Did you find any solution as I am having the same issue.
