### ISSUE TITLE
Divide by zero exception when having CVCalendar as a subview of a toggle-able parent view

### ISSUE THREAD

**Issue by Huy-Vu** [CVCalendar/CVCalendar#523]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of CVCalendar.
- [x ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.  Having CVCalendar as a subview of a toggle-able parent view
2. When toggling it parent view , CVCalendarMonthContentViewController scrollViewDidScroll get call, and since scrollView.frame.width is zero now, we will have exception in this logic

 ```
 let page = Int(floor((scrollView.contentOffset.x -
                scrollView.frame.width / 2) / scrollView.frame.width) + 1)
 ```

Solution: only change current page` if scrollView.frame.width != 0`

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by bandess** [comment]
this issue still exists and you will face it if you install the current version.

**Comment by elsesiy** [comment]
@bandess Contributions are welcome, please feel free to submit a PR.
