### ISSUE TITLE
App crashes when I added a dotmarker

### ISSUE THREAD

**Issue by tiagorc** [CVCalendar/CVCalendar#526]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## What im doing
I'm using 1.6.1v
Added CVCalendarViewDelegate, CVCalendarMenuViewDelegate, CVCalendarViewAppearanceDelegate to view controller and implementing those methods:
    func presentationMode() -> CalendarMode 
    func firstWeekday() -> Weekday 
    func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) 
    func dotMarker(shouldMoveOnHighlightingOnDayView dayView: DayView) -> Bool 
    func dotMarker(shouldShowOnDayView dayView: DayView) -> Bool 
    func dotMarkerColor() -> UIColor

## Current Behavior
Added a dummy logic to show dots in some dayWeeks but app crashes at CVCalendarDayView(L: 299) 
Tells colors variable is nil
## Possible Solution
I just put let colors: [UIColor] = [.gray] hardcoded to avoid the crashes, but im doing it right? What can i do?

## Your Environment

Latest versions
Xcode: Version 9.4.1 (9F2000)
iOS: 11.4
CVCalendar: 1.6.1

**Comment by ccortessanchez** [comment]
May sound weird but, have you checked that you have 3 or less dots for each dayview with dot markers?
