### ISSUE TITLE
Strange look  at init of calendar 

### ISSUE THREAD

**Issue by yehiabairm** [CVCalendar/CVCalendar#527]
- [ done] I have verified there are no duplicate active or recent bugs, questions, or requests
- [done ] I have verified that I am using the latest version of CVCalendar.
- [ done] I have given my issue a non-generic title.

## Expected Behavior

When change font color and label background in current month ex: July it doesn't apply changes in next month "August" until I go to October then back to it, I think it should configure delegate methods to all views and next views 

## Possible Solution
just want to know how to reload next and prev month on creation to get updates 

## Steps to Reproduce (for bugs)

1. just add a calendar to table view cell
2. modify calendar in delegate methods inside tableviewcell class
3. it's updated well in next month but strange behavior on next and prev month until I scroll a lot then back it fixes automatically 
4.

## Context

Just want to have normal calendar confirm app colors 

## Your Environment

* Version used (Cocoapods spec): 1.6.1
* Device used i.e. iPhone 6S: iPhone 7 and iPhone X
* Physical device (y/n): yes
* Link to your project (if available): not available

**Comment by zierka** [comment]
See #351 for the fix.
