### ISSUE TITLE
Last or next month selection not properly selecting the date after navigating to the month.

### ISSUE THREAD

**Issue by karuna2302** [CVCalendar/CVCalendar#528]
- [*] I have verified there are no duplicate active or recent bugs, questions, or requests
- [*] I have verified that I am using the latest version of CVCalendar.
- [*] I have given my issue a non-generic title.

## Expected Behavior
Selecting next or previous month date it should take the user to selected date in the particular month.
Single selection option.
Enabling "shouldAutoSelectDayOnMonthChange"

## Current Behavior
It always selecting first day of the month when it get presented.

## Possible Solution
If it's other then current month we should have selection based on selection date.

## Steps to Reproduce (for bugs)
1. Launch monthly view calendar 
2. Enable "shouldAutoSelectDayOnMonthChange"
3. Select next month date, It will take you to next month selection of first date.

## Context
It's blocking the user experience of the application.

## Your Environment
* Version used (Cocoapods spec): 1.5.0.
* Device used i.e. iPhone 6S: All device
* Physical device (y/n):y
* Link to your project (if available):

**Comment by elsesiy** [comment]
@karuna2302 Please feel free to submit a PR.
