### ISSUE TITLE
Calling toggleViewWithDate() sets DayViews which are unselectable to the selectable color

### ISSUE THREAD

**Issue by 96imranahmed** [CVCalendar/CVCalendar#531]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behaviour
Toggles to today's date. Unselectable days (i.e. days past today) are grayed-out (visually indicating they cannot be selected) and today's date appears selected. 

## Current Behavior
Toggles to today's date. Unselectable days (i.e. days past today) are black (visually indicating they can be selected) and today's date appears selected.

## Possible Solution
Requires a monthview refresh somewhere, though I'm not sure why the color scheme isn't being passed through in the method as in the repo.

## Steps to Reproduce
1) Set latest selectable date as today in App Delegate
2) Call toggleViewWithDate(CVDate(date: Date())) [or any other date in current month] in ViewDidAppear()
3) Dates after today appear black (i.e. selectable) with default colors, though they cannot be actually selected. They do not appear grayed out. Scrolling to another month and returning to the same month solves the issue due to MonthView refresh.

## Your Environment
* Version used (Cocoapods spec): 1.6.1
* Device used i.e. iPhone 6S: (Appears on all simulators)
* Physical device (y/n): N

**Comment by narendrajagne** [comment]
How to enable previous day's (i.e. days past today) selection ?

**Comment by 96imranahmed** [comment]
Any insights on this, at all?
