### ISSUE TITLE
Selected day not highlighting when switching month on non-range selection

### ISSUE THREAD

**Issue by remysanfeliu** [CVCalendar/CVCalendar#532]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of CVCalendar.
- [X] I have given my issue a non-generic title.

## Expected Behavior
The range selection is disabled, autoselect day on month change is disabled.
After a selection has been performed by the user, the selected day highlights. When the user switches to another month, the new month appears, but the selected day has been left unchanged by the user (thus belonging to the previous month). When the user swipes back to the initial month, the selected day is still highlighted as it was right after the user selected it.

## Current Behavior
When the user navigates back to the initial month, the selected day is not highlighted. When trying to touch it, nothing happens. When trying to set the active day by code on monthChanged, nothing happens (no toggling).

## Possible Solution
CVCalendarMonthContentViewController@l.265 : comment states that the selectedDayView should be nil if shouldAutoSelectDayOnMonthChange is disabled, but it's not.

## Steps to Reproduce (for bugs)
1. Grab the sample app
2. Set the shouldSelectRange to false
3. Start the app, select a day in the current month
4. Navigate to another month
5. Come back to the initial month
6. The day is not highlighted anymore. Try to select it, nothing happens.

## Context
I'm using the calendar as a selector to display a list of items in a dedicated table view beside the calendar. When selecting a day, the uitableview refreshes to display the content for the relevant day.

## Your Environment
* Version used (Cocoapods spec): 1.6.1
* Device used i.e. iPhone 6S: iPhopne SE, XCode 10.0 beta 5 and XCode 9.4.1, iOS 11.4 & iOS 12.0
* Physical device (y/n): n
* Link to your project (if available): Private

**Comment by elsesiy** [comment]
@remysanfeliu Thanks for this details bug report. From what you describe it's related to #485 for which there is a bugfix in the making (see [here](https://github.com/CVCalendar/CVCalendar/tree/bugfix/issue-485)). Would you mind trying with this version?
