### ISSUE TITLE
I can't setup CVCalendar

### ISSUE THREAD

**Issue by nikolaymac** [CVCalendar/CVCalendar#533]
I made all.

   ```
 @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!

```
and 
` override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        menuView.commitMenuViewUpdate()
        calendarView.commitCalendarViewUpdate()
    }`

but I don't see calendar. I see only white view on the top

**Comment by learner25** [comment]
@nikolaymac did your problem solve? got stuck in same problem

**Comment by nikolaymac** [comment]
yes! I find solution :) They forgot about delegate in Docs.  Add CVCalendarViewDelegate,CVCalendarMenuViewDelegate

and this methods
func presentationMode() -> CalendarMode {
        return .monthView
    }
    
    func firstWeekday() -> Weekday {
        return .monday
    }
