### ISSUE TITLE
make date property public in CVDate class

### ISSUE THREAD

**Issue by muhasturk** [CVCalendar/CVCalendar#534]
I wanna get selected date as Foundation.Date object and customise it inside _didSelectDayView_ delegate method.

_globalDescription_ or _commonDescription_ is not suitable for my requirements. 

Can you please make 'date' property public?

**Comment by elsesiy** [comment]
@muhasturk Can you please elaborate a little bit on why this would be useful? Thanks!

**Comment by hipwelljo** [comment]
You can call the convertedDate function on CVDate to get a Date.

**Comment by elsesiy** [comment]
As @hipwelljo says there's a way to access the underlying `Foundation.Date` so I don't see the need for public property access. Please comment if further assistance is needed, thanks!
