### ISSUE TITLE
Add suffix text on the date cell?

### ISSUE THREAD

**Issue by nirajhi** [CVCalendar/CVCalendar#542]
Hello,

  I want to add the text(i.e day) to include other dates along with Georgian date. Is it possible?
![cvcalendarissue](https://user-images.githubusercontent.com/2114194/47600422-84e06400-d9e0-11e8-9af1-1fa425162575.png)

Thanks,
Niraj

**Comment by elsesiy** [comment]
@nirajhi Please use the issue template and properly provide all info needed. Thanks!
