### ISSUE TITLE
Top markers disappear upon beginning to swipe to new month

### ISSUE THREAD

**Issue by hipwelljo** [CVCalendar/CVCalendar#543]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Behavior
When I start to swipe between months, the top markers disappear. The next month's top markers are visible while swiping, and remain visible upon releasing the touch, but as soon as I begin to swipe again that month's top markers disappear.

I'm not sure the cause of the issue. But perhaps it's related to the fact it's only 0.5pt tall. I would love the ability to set its height - I would use 1pt for example.

## Steps to Reproduce
1. Create a calendar month view with topMarkerShouldDisplayOnDayView returning true
2. Begin to swipe the calendar
Results: Top markers disappear for this month, but are visible for the upcoming month

![ezgif-1-d18f507031b4](https://user-images.githubusercontent.com/6282848/48094010-33995700-e1ce-11e8-94b4-19bb5bc9de93.gif)

## Your Environment
* Version used: 1.6.2
* Device used: Simulator (iOS 12.1)

**Comment by elsesiy** [comment]
@hipwelljo I released `1.6.2` today which include a couple of fixes around the layouting/drawing of views. Please test again and use a real device, thanks.

**Comment by hipwelljo** [comment]
Hey @elsesiy thanks for the release! I tested it and confirmed I see the same behavior originally reported in 1.6.2 unfortunately.

**Comment by hipwelljo** [comment]
Thou shall not be stale

**Comment by hipwelljo** [comment]
Thou shall not be stale

**Comment by hipwelljo** [comment]
Thou shall not be stale

**Comment by elsesiy** [comment]
@hipwelljo I'm not actively working on this project anymore. If you're able to fix it yourself then please submit a PR.

**Comment by kevalvadoliya** [comment]
I have fixed the issue. [PR:558](https://github.com/CVCalendar/CVCalendar/pull/588)
