### ISSUE TITLE
Calendar view misbehaving while changing mode(Week/Month)

### ISSUE THREAD

**Issue by venkatmca99** [CVCalendar/CVCalendar#545]
Hi Team,

I am using CVCalendar framework in my project( Using Xcode 9.4 and swift3), but I am facing issues while we changing calendar mode from week to month and vice-versa
Please find the screenshots for your reference 

Following are the steps
1. Opened calendar week mode in my app
2. Minimize app and lock the screen for around 20 min
3. Then unlock the phone and open the app, where we are facing this issue.

**NOTE:- We are using the same constraints as in the demo project.**

Any Help would be appreciated.

![screen shot 2018-11-14 at 11 17 09 am](https://user-images.githubusercontent.com/25770138/48463304-9d82b380-e801-11e8-9666-e9f327615c2d.png)
![screen shot 2018-11-14 at 11 17 28 am](https://user-images.githubusercontent.com/25770138/48463308-9e1b4a00-e801-11e8-9e14-5f7386a222fa.png)

**Comment by elsesiy** [comment]
@venkatmca99 I have no idea which version of the library you're using. Can you please provide a sample application so I can reproduce this? Thanks.

**Comment by venkatmca99** [comment]
Thanks for the reply.

We are using below versions
Xcode: 9.4
CVcalendar library: Swift 3

And we can't provide source code because it's client application.
