### ISSUE TITLE
Not able to select today date

### ISSUE THREAD

**Issue by ghouse1** [CVCalendar/CVCalendar#547]
What is the delegate method which fire, when select today day from day view.

I try to check with below delegate method but it fires when select next days only.

 ```
func didSelectDayView(_ dayView: CVCalendarDayView, animationDidFinish: Bool) {
        selectedDay = dayView
    }
```

**Comment by ccortessanchez** [comment]
You need to use convertedDate method
`selectedDay = dayView.date.convertedDate()`

**Comment by elsesiy** [comment]
@ccortessanchez Thanks for helping fellow users out! @ghouse1 please comment if further help is needed.
