### ISSUE TITLE
Not able to access CVdate in objective C class

### ISSUE THREAD

**Issue by jyotsnakadam** [CVCalendar/CVCalendar#548]
Hi Team,
I am using CVCalendar version 1.6.1. with SWIFT 4.0
I have old objective-c project for maintenance. But Now I am getting error while accessing the CVCalendar view classes 
Errors are:
1.  No visible @interface for 'CVDate' declares the selector 'initWithDate:calendar:'
2. Property 'contentController' not found on object of type 'CVCalendarView *'
3. No visible @interface for 'CVCalendarView' declares the selector 'commitCalendarViewUpdate'
4. No visible @interface for 'CVCalendarMenuView' declares the selector 'commitMenuViewUpdate'
5. No visible @interface for 'CVCalendarView' declares the selector 'loadPreviousView'
I have XCode 9.2

Please suggest me what needs to be done as I am stuck due to this issued not able to run my application.
Regards,
Jyotsna Kadam

**Comment by elsesiy** [comment]
@jyotsnakadam I haven't used the project with Objective-C in a while, can you provide a sample by any chance so I can reproduce this? Thanks!

**Comment by manjuhere** [comment]
Same Here... @jyotsnakadam did you, by any chance try migrating to swift 4 before this happened? I was on CVCalendar 1.5.2 as it was an old project. tried and failed Xcode migration to swift 4. Hence switched to 1.6.2... now facing this issue.

**Comment by elsesiy** [comment]
@manjuhere Can you please provide a sample project? Thanks!

**Comment by manjuhere** [comment]
Here's what I did -

1. Initialised a new objective C project from Xcode 10. changed project compatibility to mirror existing project (Xcode 3.2+) with the issue.
2. Added CVCalendar 1.5.2 Pod. Soon after adding this pod, I get errors on building, as CVCalendar target in Pods Project has swift version set to 4.2. but the pod 1.5.2 is from swift 3 branch
3. To fix errors, Change Swift version to 3 for 'CVCalendar' Target in Pods Project. This will trigger a warning to convert to swift 4 syntax to avoid deprecation...
4. Now, Select CVCalendar target and Edit > Convert to Modern Swift Syntax. 
- When I select '**Minimal Inference**' & save - I am able to reproduce same errors only when i change '**Swift 3 @objc inference**' build setting set to default/off. Xcode even throws a warning for keeping this on.
- When I select '**Match Swift 3 Behaviour**' & save - it's converted properly albeit a few minor warnings.

sample repo here... https://github.com/manjuhere/CVSample .
You can go through the commits to see the steps. will be glad to help you further on this
