### ISSUE TITLE
How to disable scrolling before and after a particular date in week view. I have tried to use disableScrollingBeforeDate and earliest selectable date delegate method but didn't work

### ISSUE THREAD

**Issue by nikita-11-04** [CVCalendar/CVCalendar#556]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by ccortessanchez** [comment]
Do you have any source code to test it?

**Comment by nikita-11-04** [comment]
func setUpCVCalendar()
  {
    calendarView.calendarDelegate = self
    calendarMenuView.delegate = self
    self.calendarMenuView.commitMenuViewUpdate()
    self.calendarView.calendarAppearanceDelegate = self
    self.calendarView.delegate = self
    
    self.calendarView.commitCalendarViewUpdate()
    
  }
  func latestSelectableDate() -> Date {
        let dateStr = projectCreationDate// Date after which all dates will get disabled

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let date = dateFormatter.date(from:dateStr)!
        let calendar = Calendar.current
        let components = calendar.dateComponents([.year, .month, .day, .hour], from: date)
        let startDate = calendar.date(from:components)

        return startDate!
  }
  
  func earliestSelectableDate() -> Date {

    let dateStr = projectCreationDate// Date after which all dates will get disabled

    let dateFormatter = DateFormatter()
    dateFormatter.dateFormat = "yyyy-MM-dd"
    let date = dateFormatter.date(from:dateStr)!
    let calendar = Calendar.current
    let components = calendar.dateComponents([.year, .month, .day, .hour], from: date)
    let startDate = calendar.date(from:components)

    return startDate!
  }

  func presentationMode() -> CalendarMode {
    return CalendarMode.weekView
  }
  
  
  
  func firstWeekday() -> Weekday {
    return CVCalendarWeekday.sunday
  }

**Comment by davcpas1234** [comment]
This is still an issue, originally raised in #522
