### ISSUE TITLE
Can't set calendarView with constraints programmatically

### ISSUE THREAD

**Issue by alejoforeslucey** [CVCalendar/CVCalendar#558]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

I'm using TinyConstraints to get the calendar view to be centered:

```
calendarView.centerXToSuperview()
calendarView.topToBottom(of: menuView, offset: 16)
calendarView.widthToSuperview()
calendarView.height(450)
```

I'm expecting to run the app and see the calendar, as using the same constraints menuView shows up, but instead, the app crashes as soon as it launches.

The error is marked by Xcode in CVCalendarMonthContentViewController.swift, in:
```
public func scrollViewDidScroll(_ scrollView: UIScrollView) {
...
// Here the error says Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
   let page = Int(floor((scrollView.contentOffset.x - scrollView.frame.width / 2) / scrollView.frame.width) + 1)
...
}
```

Please help!

**Comment by elsesiy** [comment]
What's your target platform? If it's iOS 10 then #557 seems to be a fix for it.
