### ISSUE TITLE
Detect when date is pressed, and get the date

### ISSUE THREAD

**Issue by xScylez** [CVCalendar/CVCalendar#561]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of CVCalendar.
- [x ] I have given my issue a non-generic title.

How can I detect when a date is pressed, and print the date value? I tried using this:

```
func didSelectDayView(dayView: CVCalendarDayView) {
        print("yay")
}
```
But when selecting a date in the CalendarView, it doesn't print anything.

**Comment by ccortessanchez** [comment]
Did you set the delegates properly?

**Comment by xScylez** [comment]
@ccortessanchez I have added it like this:

`func ViewController: UIViewController, CVCalendarViewDelegate, CVCalendarMenuViewDelegate {`

**Comment by ccortessanchez** [comment]
I'm guessing you add this two lines somewhere in your viewDidLoad method
`calendarView.delegate = self
menuView.delegate = self`

**Comment by xScylez** [comment]
@ccortessanchez I have this:

```
    override func viewDidLoad() {
        super.viewDidLoad()

        // Code below

        // Appearance delegate [Unnecessary]
        self.calendarView.calendarAppearanceDelegate = self

        // Animator delegate [Unnecessary]
        self.calendarView.animatorDelegate = self

        // Menu delegate [Required]
        self.menuView.menuViewDelegate = self

        // Calendar delegate [Required]
        self.calendarView.calendarDelegate = self
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        // Commit frames' updates
        self.menuView.commitMenuViewUpdate()
        self.calendarView.commitCalendarViewUpdate()
    }
```

**Comment by xScylez** [comment]
This worked:

```
    func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) {
        print("kfkf")
    }
```

But how do I get the the exact date that is selected? I have stored value in Realm that I want to show up when the specific date is selected, and I have also stored date values in Realm. How can I do that?

**Comment by ccortessanchez** [comment]
> This worked:
> 
> ```
>     func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) {
>         print("kfkf")
>     }
> ```
> But how do I get the the exact date that is selected? I have stored value in Realm that I want to show up when the specific date is selected, and I have also stored date values in Realm. How can I do that?

You can get the selected day view date like this 
`
var calendar = Calendar.current
calendar.locale = Locale.current
calendar.timeZone = TimeZone(identifier: Constants.TimeZone.UTC)! // Here use your time zone
let date = dayView.date.convertedDate(calendar: calendar)

`

**Comment by xScylez** [comment]
> var calendar = Calendar.current
> calendar.locale = Locale.current
> calendar.timeZone = TimeZone(identifier: Constants.TimeZone.UTC)! // Here use your time zone
> let date = dayView.date.convertedDate(calendar: calendar)

Where did you get Constants from? I get error: `Use of unresolved identifier 'Constants' `

**Comment by xScylez** [comment]
@ccortessanchez Worked, thanks!

**Comment by xScylez** [comment]
@ccortessanchez Worked, thanks!
