### ISSUE TITLE
Change presentationMode and save for next time

### ISSUE THREAD

**Issue by xScylez** [CVCalendar/CVCalendar#564]
Currently I am using this:
```
    func presentationMode() -> CalendarMode {
        return .monthView
    }
```

And I have these two buttons:
```
    @IBAction func week(_ sender: Any) {
        calendarView.changeMode(.weekView)
    }
    
    @IBAction func month(_ sender: Any) {
        calendarView.changeMode(.monthView)
    }
```

How can I save the mode that the user choose? So if It choose weekView, it will open as weekView next time the app opens?

**Comment by elsesiy** [comment]
@xScylez Can you please use the issue template? I have no idea what your setup looks like and what you have tried already but this shouldn't be a big issue. Please edit this issue or create a new one.

**Comment by xScylez** [comment]
> @xScylez Can you please use the issue template? I have no idea what your setup looks like and what you have tried already but this shouldn't be a big issue. Please edit this issue or create a new one.

Currently I am using the example project for testing purpose, so the setup is default as the example.

**Comment by ccortessanchez** [comment]
I don't think the thing you want is related to the CVCalendar project. You can save the selected presentation mode in User Defaults and load it every time you open the app

**Comment by xScylez** [comment]
@ccortessanchez I have tried that, but the `presentationMode()` needs to be ran. I can change it in the `viewDidLoad()` but then it will change after everything is loaded, and that doesn't look professional at all.

**Comment by ccortessanchez** [comment]
> @ccortessanchez I have tried that, but the `presentationMode()` needs to be ran. I can change it in the `viewDidLoad()` but then it will change after everything is loaded, and that doesn't look professional at all.

In presentationMode() you can check the value stored in User Defaults and return the correct mode. Where did you check User Defaults then?

**Comment by xScylez** [comment]
@ccortessanchez I am not on my MAC right now, so I have to create it from what I remember, but something like this:

```
// UserDefaults.standard.integer(forKey: "value") == 0 (MonthView)
// UserDefaults.standard.integer(forKey: "value") == 1 (WeekView)


    func presentationMode() -> CalendarMode {
        if UserDefaults.standard.integer(forKey: "value") == 0 {
            return .monthView
        } else {
            return .weekView
            
        }
    }
```

If the value is 0, the CVCalendar is just black.

**Comment by ccortessanchez** [comment]
I'm guessing you store the value of selected presentation mode in both func week and func month like this:
```
UserDefaults.standard.set(true, forKey: “isWeekMode”)
```

Then you can get it like this in presentationMode()
```
let mode = UserDefaults.standard.bool(forKey: “isWeekMode”)
```

**Comment by xScylez** [comment]
@ccortessanchez So I should do something like this? :

```
    func presentationMode() -> CalendarMode {
        let mode = UserDefaults.standard.bool(forKey: “isWeekMode”)
        if mode == true {
            return .weekView
        } else {
            return .monthView
            
        }
    }
```

**Comment by ccortessanchez** [comment]
> @ccortessanchez So I should do something like this? :
> 
> ```
>     func presentationMode() -> CalendarMode {
>         let mode = UserDefaults.standard.bool(forKey: “isWeekMode”)
>         if mode == true {
>             return .weekView
>         } else {
>             return .monthView
>             
>         }
>     }
> ```

Yes, but don't forget to set the current value every time you change the presentation mode in both IBAction functions

**Comment by xScylez** [comment]
> > @ccortessanchez So I should do something like this? :
> > ```
> >     func presentationMode() -> CalendarMode {
> >         let mode = UserDefaults.standard.bool(forKey: “isWeekMode”)
> >         if mode == true {
> >             return .weekView
> >         } else {
> >             return .monthView
> >             
> >         }
> >     }
> > ```
> 
> Yes, but don't forget to set the current value every time you change the presentation mode in both IBAction functions

Just tried this now, when it's returning false, is shows the monthView, but if it turns true, the CalendarView is just black. Like this:
![Simulator Screen Shot - iPhone XS Max - 2019-03-12 at 21 22 32](https://user-images.githubusercontent.com/10552182/54233364-19b9a900-450d-11e9-9b30-3e6815995094.png)
