### ISSUE TITLE
Detect long press on date

### ISSUE THREAD

**Issue by xScylez** [CVCalendar/CVCalendar#565]
Now we have this to detect when a date is tapped:

```
func didSelectDayView(_ dayView: DayView, animationDidFinish: Bool) {

}
```

Is there any way to implement a function that detect if we long press?

**Comment by elsesiy** [comment]
@xScylez Can you please use the issue template? I have no idea what your setup looks like and what you have tried already but this shouldn't be a big issue. Please edit this issue or create a new one.

**Comment by xScylez** [comment]
> @xScylez Can you please use the issue template? I have no idea what your setup looks like and what you have tried already but this shouldn't be a big issue. Please edit this issue or create a new one.

Currently I am using the example project for testing purpose, so the setup is default as the example.
