### ISSUE TITLE
CalendarView not updated when orientation changes-with navigation controller

### ISSUE THREAD

**Issue by darshanPatel16** [CVCalendar/CVCalendar#576]
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
Bug: CalendarView should resize automatically when orientation is changed.

## Current Behavior

I am developing an app with a side menu controller for navigation change. One of the options is Calendar. I have set the auto layout constraints as it covers the full view controller.
Currently when the calendar is open in portrait mode the distance between two rows is pretty good. But, when I change to landscape mode the distance should reduce between two rows. Currently, it's not resizing the view it remains the same size as the portrait.

## Possible Solution
Not sure it will work or not, but we need to resize the `calendarView.contentController` when orientation changes.

## Steps to Reproduce (for bugs)
![Screenshot 2019-08-23 at 3 06 22 PM](https://user-images.githubusercontent.com/29564375/63583051-da14e400-c5b7-11e9-9da1-e89d5fd91ef3.png)

The gray view is the `CVCalendarMenuView`
The green view is the `CVCalendarView`
Give top, bottom, leading and trailing constraint as `0` for green view.

Portrait view screenshot:
![IMG_5413](https://user-images.githubusercontent.com/29564375/63583683-1dbc1d80-c5b9-11e9-91cc-760643153c64.PNG)

Landscape view screenshot:
![IMG_5410](https://user-images.githubusercontent.com/29564375/63583702-23b1fe80-c5b9-11e9-9867-2dcf89d0a572.PNG)

## Your Environment

* Version used (Cocoapods spec): 1.6.1
* Device used i.e. iPhone 6S: iPhone Xs Max
* Physical device (y/n): Yes
* Link to your project (if available):

**Comment by kevalvadoliya** [comment]
I was facing same issue @darshanPatel16. I updated the following answer of issue #159 and It was working for me.  
(https://github.com/CVCalendar/CVCalendar/issues/159#issuecomment-462932469)

```
extension CVCalendarView {

    public func redrawViewIfNecessarry() {
        let contentViewSize = contentController.bounds.size
        let selfSize = bounds.size
        let screenSize = UIScreen.main.bounds.size
        let allowed = selfSize.width <= screenSize.width && selfSize.height <= screenSize.height
        setNeedsLayout()
        layoutIfNeeded()
        if !allowed {
            return
        }
        let width = selfSize.width
        let height: CGFloat
        let countOfWeeks = CGFloat(6)
        guard let mode = calendarMode,
            let vSpace = appearance.spaceBetweenWeekViews,
            let hSpace = appearance.spaceBetweenDayViews else {
            return
        }
        switch mode {
        case .weekView:
            height = selfSize.height
        case .monthView:
            height = (selfSize.height / countOfWeeks) - (vSpace * countOfWeeks)
        }
        var found = false
        for constraint in constraints {
            if constraint.firstAttribute == .height {
                found = true
            }
        }
        if !found {
            addConstraint(NSLayoutConstraint(item: self,
                                             attribute: .height,
                                             relatedBy: .equal,
                                             toItem: nil,
                                             attribute: .height,
                                             multiplier: 1,
                                             constant: frame.height))
        }
        weekViewSize = CGSize(width: width, height: height)
        dayViewSize = CGSize(width: (width / 7.0) - hSpace, height: height)
        contentController.updateFrames(selfSize != contentViewSize ? bounds : CGRect.zero)
    }

}

```
```

override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        menuView.commitMenuViewUpdate()
        calendarView.redrawViewIfNecessarry()
    }
```

**Comment by darshanPatel16** [comment]
@kevalvadoliya, thanks for the help 👍🏻
