### ISSUE TITLE
CalendarMode.weekView does not display the dates

### ISSUE THREAD

**Issue by pinloop** [CVCalendar/CVCalendar#579]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
I want the calendar to use only .weekView, and I want it to look like this:
![IMG_0045_WHAT_I_WANT](https://user-images.githubusercontent.com/42355167/69326041-7009ea80-0c4b-11ea-9028-ed6b80d1c0a9.PNG)

## Current Behavior

When running app with .monthView, everything works fine, but when I run while using .weekView, the dates doesn't show up.
![IMG_0046](https://user-images.githubusercontent.com/42355167/69326076-7e580680-0c4b-11ea-8276-61c2ae0a0bfa.PNG)

## Steps to Reproduce (for bugs)
1. The only change I did when doing this is change from .monthView to .weekView

## Context
This is how it looks like when using .monthView:
![IMG_0045](https://user-images.githubusercontent.com/42355167/69326170-a7789700-0c4b-11ea-8e91-c80c3158c002.PNG)

This is how it looks like when using .weekView:
![IMG_0046](https://user-images.githubusercontent.com/42355167/69326205-b3645900-0c4b-11ea-9c2e-58c0734327be.PNG)

## Your Environment
* Device used i.e. iPhone 6S: iPhone 11 Pro Max
* Physical device (y/n): Yes

**Comment by Bella031718** [comment]
I have the same problem. Have you solved it？

**Comment by pinloop** [comment]
> I have the same problem. Have you solved it？

No, I still haven't found any solution for this.

**Comment by elsesiy** [comment]
@pinloop You didn't provide any information on which version of the library you're using. The sample application works just fine so there must be something wrong on your end. If you still need support please provide a project to reproduce the issue, thanks.
