### ISSUE TITLE
I have added like in document, but I could not see any thing

### ISSUE THREAD

**Issue by muga87** [CVCalendar/CVCalendar#581]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by muga87** [comment]
I have added two UIViews and named as told like in document. but I could not see any thing just black.

**Comment by elsesiy** [comment]
@muga87 Please use the issue template, otherwise I can't provide any support sorry.
