### ISSUE TITLE
Will CVCalendar support Arabic(RTL)? Means if the selected language is Arabic, I need to show the calendar in RTL format with Arabic digits. Is it possible?

### ISSUE THREAD

**Issue by hilajqinnovation** [CVCalendar/CVCalendar#582]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.

## Expected Behavior
 
want to display the calendar in RTL with Arabic font support and display the calendar dates in Ararbic

## Current Behavior
 
Now RTL is working when I gave calendarView.semanticContentAttribute = .forceRightToLeft. But the digits(calendar dates still not changed to Arabic).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by elsesiy** [comment]
No RTL support but please feel free to add it!
