### ISSUE TITLE
CVCalendar has no Package.swift manifest for version 1.6.2

### ISSUE THREAD

**Issue by Dilan-Anuruddha** [CVCalendar/CVCalendar#583]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of CVCalendar.
- [ ] I have given my issue a non-generic title.
![Screenshot 2019-12-23 at 14 18 28](https://user-images.githubusercontent.com/47709400/71346940-2afd0f00-258f-11ea-935a-23934331e0d7.png)

**Comment by elsesiy** [comment]
@Dilan-Anuruddha That's correct, the project is not distributed via Swift Package Manager due to it's heavy reliance on `UIKit` which still seemed to be hard to deal with via SPM. If you have an idea on how to solve this, please submit a PR!

**Comment by smartcat32** [comment]
Please see the latest answers to [this SO question](https://stackoverflow.com/questions/34778823/swift-package-manager-uikit-dependency)
