### ISSUE TITLE
SwiftUI support

### ISSUE THREAD

**Issue by ralfebert** [CVCalendar/CVCalendar#594]
It would be great if CVCalendar would come with a SwiftUI wrapper component.

As a starter, I did a simple wrapper to show a monthly calendar sheet:
https://stackoverflow.com/questions/61857101/monthly-calender-sheet-in-swiftui/61857102#61857102

**Comment by elsesiy** [comment]
Thanks @ralfebert, I agree that this would be a nice addition.
Unfortunately I don't have the time to add it so please feel free to submit a PR, thanks.
