### ISSUE TITLE
WeekView does not pick a day while switching between April and May

### ISSUE THREAD

**Issue by martjemeyer** [CVCalendar/CVCalendar#71]
It might have to do with a combination of the currently selected day, since I can't reproduce it on future months. And since it does not pick a day, it won't update my columns for that week.

I made a GIF to show what I mean.
![weekview demo](https://cloud.githubusercontent.com/assets/9798987/7553616/a57c7528-f703-11e4-909e-052f6768fdf0.gif)

**Comment by Mozharovsky** [comment]
Hello @martjemeyer, 

It seems like I can't reproduce the issue you have with the latest code on develop branch. Did you set WeekView mode initially or did it appear on mode change? 

Regards, 
Eugene

**Comment by martjemeyer** [comment]
I believe it has something to do with the region settings. My region is Sweden, but it is also happends if I change to a few other europe countries. And some it does not. Maybe those countries, who has standard Monday as the begin of a week the bug appears?

Try to set the region settings to Sweden like in the screenshot and see if you can reproduce it. I'm using a build of the last week.
![screenshot 2015-05-11 23 35 18](https://cloud.githubusercontent.com/assets/9798987/7575652/b641107e-f836-11e4-9c2d-62bfded934f6.png)

**Comment by martjemeyer** [comment]
It has not todo with which month it is, it only happends to the weeks just before the current week with the current region settings.
Were you able to reproduce it?
