### ISSUE TITLE
Dot marker on current day appears above it, not below

### ISSUE THREAD

**Issue by thomasbaldwin** [CVCalendar/CVCalendar#87]
Not exactly sure why this happens, but if you either remove these lines from the setupDotMarker function

```
                if self == coordinator.selectedDayView {
                    moveDotMarkerBack(false, coloring: false)
                }
```

or you simply change the line to this

```
                if self == coordinator.selectedDayView {
                    moveDotMarkerBack(true, coloring: false)
                }
```

it fixes the issue.
# Screenshots of the problem

Look at June 12th

![screen shot 2015-06-12 at 4 49 38 pm](https://cloud.githubusercontent.com/assets/5099084/8139628/1bbd1830-1123-11e5-9f1c-324e2f39199a.png)

And if you click on the day

![screen shot 2015-06-12 at 4 49 49 pm](https://cloud.githubusercontent.com/assets/5099084/8139636/29fee7de-1123-11e5-9afb-ac0458620d78.png)

**Comment by Mozharovsky** [comment]
Hello @thomasbaldwin, 

Thank you for your contributions into this project! It means a lot for me! 

I'll take a look at this bug. :) 

Regards, 
Eugene

**Comment by johnjiang** [comment]
I'm still encountering this issue on 1.2.8. Does #115 really fix this bug?
