### ISSUE TITLE
AutoLayout Layout Constrain not working

### ISSUE THREAD

**Issue by prabhatk** [CVCalendar/CVCalendar#95]
Hello Friends,

i found that this CVCalenderView is not supporting the orientation with Auto layout constrains, like it has width of 300pt in portrait mode but as i change orientation it became of 600 width but after scrolling two or three months whole component got screwed.

Please find attached screen shots
![ios simulator screen shot 14-jul-2015 8 20 46 am](https://cloud.githubusercontent.com/assets/246486/8676958/535766be-2a01-11e5-8cb6-967c465b0c30.png)
![ios simulator screen shot 14-jul-2015 8 20 37 am](https://cloud.githubusercontent.com/assets/246486/8676956/535503b0-2a01-11e5-8b87-080e68dac1cd.png)
![ios simulator screen shot 14-jul-2015 8 20 27 am](https://cloud.githubusercontent.com/assets/246486/8676957/5356484c-2a01-11e5-81c0-c799c2258550.png)
![ios simulator screen shot 14-jul-2015 8 20 21 am](https://cloud.githubusercontent.com/assets/246486/8676959/5359448e-2a01-11e5-80da-686c6e130e37.png)

**Comment by Mozharovsky** [comment]
Hello @prabhatk, 

CVCalendar does not provide extra calculations on orientation change. It will be added as soon as possible! Keep watching. 

Regards, 
Eugene
