### ISSUE TITLE
CVCalendarView in TableView Header in width not stretching

### ISSUE THREAD

**Issue by MakeHui** [CVCalendar/CVCalendar#96]
![qq20150715-1](https://cloud.githubusercontent.com/assets/8622405/8690496/d5e1f3f6-2ae7-11e5-8039-d51a866a1fb4.png)

**Comment by Mozharovsky** [comment]
Hello @MakeHui,

Please check out  [develop](https://github.com/Mozharovsky/CVCalendar/tree/develop)  and issued #101 #104 #97. It should help!

Regards, 
Eugene
